'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace LightSwitchApplication.Implementation
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class ApplicationDataDataService
        Inherits Global.Microsoft.LightSwitch.ServerGenerated.Implementation.DataService(Of Global.LightSwitchApplication.Implementation.ApplicationData)
    
        Public Sub New()
            MyBase.New()
        End Sub
    
        Protected Overrides Function GetDataService(dataWorkspace As Global.Microsoft.LightSwitch.IDataWorkspace) As Global.Microsoft.LightSwitch.IDataService
            Return DirectCast(dataWorkspace, Global.LightSwitchApplication.DataWorkspace).ApplicationData
        End Function
    
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class ApplicationDataServiceImplementation
        Inherits Global.Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation(Of Global.LightSwitchApplication.Implementation.ApplicationData)
    
        Public Sub New(ByVal dataService As Global.Microsoft.LightSwitch.IDataService)
            MyBase.New(dataService)
        End Sub
    
    #Region "Queries"
    #End Region

    #Region "Protected methods"
        Protected Overrides Function CreateObject(ByVal type As Global.System.Type) As Object
            If (GetType(Global.LightSwitchApplication.Implementation.Chofer).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.Chofer
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.Viaje).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.Viaje
            End If
    
            Return MyBase.CreateObject(type)
        End Function
    
        Protected Overrides Function CreateObjectContext() As Global.LightSwitchApplication.Implementation.ApplicationData
            Dim assemblyName As String = Global.System.Reflection.Assembly.GetExecutingAssembly().GetName().Name
            Return New Global.LightSwitchApplication.Implementation.ApplicationData(Me.GetEntityConnectionString( _
                "_IntrinsicData", _
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl", _
                "System.Data.SqlClient", _
                True))
        End Function
    
        Protected Overrides Function CreateEntityImplementation(Of T As Global.Microsoft.LightSwitch.IEntityObject)() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Chofer)) Then
                Return New Global.LightSwitchApplication.Implementation.Chofer()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Viaje)) Then
                Return New Global.LightSwitchApplication.Implementation.Viaje()
            End If
            Return Nothing
        End Function
    
    #End Region
    
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class NorthwindDataDataService
        Inherits Global.Microsoft.LightSwitch.ServerGenerated.Implementation.DataService(Of Global.LightSwitchApplication.Implementation.NorthwindData)
    
        Public Sub New()
            MyBase.New()
        End Sub
    
        Protected Overrides Function GetDataService(dataWorkspace As Global.Microsoft.LightSwitch.IDataWorkspace) As Global.Microsoft.LightSwitch.IDataService
            Return DirectCast(dataWorkspace, Global.LightSwitchApplication.DataWorkspace).NorthwindData
        End Function
    
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class NorthwindDataServiceImplementation
        Inherits Global.Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation(Of Global.LightSwitchApplication.Implementation.NorthwindData)
    
        Public Sub New(ByVal dataService As Global.Microsoft.LightSwitch.IDataService)
            MyBase.New(dataService)
        End Sub
    
    #Region "Queries"
    #End Region

    #Region "Protected methods"
        Protected Overrides Function CreateObject(ByVal type As Global.System.Type) As Object
            If (GetType(Global.LightSwitchApplication.Implementation.CategoriesItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.CategoriesItem
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.CustomerCustomerDemoItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.CustomerCustomerDemoItem
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.CustomerDemographicsItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.CustomerDemographicsItem
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.CustomersItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.CustomersItem
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.EmployeesItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.EmployeesItem
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.EmployeeTerritoriesItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.EmployeeTerritoriesItem
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.Order_DetailsItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.Order_DetailsItem
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.OrdersItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.OrdersItem
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.ProductsItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.ProductsItem
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.RegionItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.RegionItem
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.ShippersItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.ShippersItem
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.SuppliersItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.SuppliersItem
            End If
            If (GetType(Global.LightSwitchApplication.Implementation.TerritoriesItem).Equals(type)) Then
                Return New Global.LightSwitchApplication.Implementation.TerritoriesItem
            End If
    
            Return MyBase.CreateObject(type)
        End Function
    
        Protected Overrides Function CreateObjectContext() As Global.LightSwitchApplication.Implementation.NorthwindData
            Dim assemblyName As String = Global.System.Reflection.Assembly.GetExecutingAssembly().GetName().Name
            Return New Global.LightSwitchApplication.Implementation.NorthwindData(Me.GetEntityConnectionString( _
                "NorthwindData", _
                "res://" + assemblyName + "/NorthwindData.csdl|res://" + assemblyName + "/NorthwindData.ssdl|res://" + assemblyName + "/NorthwindData.msl", _
                "System.Data.SqlClient", _
                True))
        End Function
    
        Protected Overrides Function CreateEntityImplementation(Of T As Global.Microsoft.LightSwitch.IEntityObject)() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.CategoriesItem)) Then
                Return New Global.LightSwitchApplication.Implementation.CategoriesItem()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.CustomerCustomerDemoItem)) Then
                Return New Global.LightSwitchApplication.Implementation.CustomerCustomerDemoItem()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.CustomerDemographicsItem)) Then
                Return New Global.LightSwitchApplication.Implementation.CustomerDemographicsItem()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.CustomersItem)) Then
                Return New Global.LightSwitchApplication.Implementation.CustomersItem()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.EmployeesItem)) Then
                Return New Global.LightSwitchApplication.Implementation.EmployeesItem()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.EmployeeTerritoriesItem)) Then
                Return New Global.LightSwitchApplication.Implementation.EmployeeTerritoriesItem()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.Order_DetailsItem)) Then
                Return New Global.LightSwitchApplication.Implementation.Order_DetailsItem()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.OrdersItem)) Then
                Return New Global.LightSwitchApplication.Implementation.OrdersItem()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.ProductsItem)) Then
                Return New Global.LightSwitchApplication.Implementation.ProductsItem()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.RegionItem)) Then
                Return New Global.LightSwitchApplication.Implementation.RegionItem()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.ShippersItem)) Then
                Return New Global.LightSwitchApplication.Implementation.ShippersItem()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.SuppliersItem)) Then
                Return New Global.LightSwitchApplication.Implementation.SuppliersItem()
            End If
            If GetType(T).Equals(GetType(Global.LightSwitchApplication.TerritoriesItem)) Then
                Return New Global.LightSwitchApplication.Implementation.TerritoriesItem()
            End If
            Return Nothing
        End Function
    
    #End Region
    
    End Class
    
    
    #Region "DataServiceImplementationFactory"
    <Global.System.ComponentModel.Composition.PartCreationPolicy(Global.System.ComponentModel.Composition.CreationPolicy.Shared)> _
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Internal.IDataServiceFactory))> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class __DataServiceFactory
        Inherits Global.Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    
        Protected Overrides Function CreateDataService(ByVal dataServiceType As Global.System.Type) As Global.Microsoft.LightSwitch.IDataService
            If dataServiceType.Equals(GetType(Global.LightSwitchApplication.ApplicationDataService)) Then
                Return New Global.LightSwitchApplication.ApplicationDataService()
            End If
            If dataServiceType.Equals(GetType(Global.LightSwitchApplication.NorthwindDataService)) Then
                Return New Global.LightSwitchApplication.NorthwindDataService()
            End If
            Return MyBase.CreateDataService(dataServiceType)
        End Function
    
        Protected Overrides Function CreateDataServiceImplementation(Of TDataService As Global.Microsoft.LightSwitch.IDataService)(ByVal dataService As TDataService) As Global.Microsoft.LightSwitch.Internal.IDataServiceImplementation
            If GetType(TDataService).Equals(GetType(Global.LightSwitchApplication.ApplicationDataService)) Then
                Return New Global.LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService)
            End If
            If GetType(TDataService).Equals(GetType(Global.LightSwitchApplication.NorthwindDataService)) Then
                Return New Global.LightSwitchApplication.Implementation.NorthwindDataServiceImplementation(dataService)
            End If
            Return MyBase.CreateDataServiceImplementation(dataService)
        End Function
    End Class
    #End Region
    
    <Global.System.ComponentModel.Composition.PartCreationPolicy(Global.System.ComponentModel.Composition.CreationPolicy.Shared)> _
    <Global.System.ComponentModel.Composition.Export(GetType(Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider))> _
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Class __TypeMapping
        Implements Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider
        Private Function GetImplementationType(ByVal definitionType As Global.System.Type) As Global.System.Type Implements Global.Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType
            If GetType(Global.LightSwitchApplication.Chofer).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Chofer)
            End If
            If GetType(Global.LightSwitchApplication.Viaje).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Viaje)
            End If
            If GetType(Global.LightSwitchApplication.CategoriesItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.CategoriesItem)
            End If
            If GetType(Global.LightSwitchApplication.CustomerCustomerDemoItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.CustomerCustomerDemoItem)
            End If
            If GetType(Global.LightSwitchApplication.CustomerDemographicsItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.CustomerDemographicsItem)
            End If
            If GetType(Global.LightSwitchApplication.CustomersItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.CustomersItem)
            End If
            If GetType(Global.LightSwitchApplication.EmployeesItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.EmployeesItem)
            End If
            If GetType(Global.LightSwitchApplication.EmployeeTerritoriesItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.EmployeeTerritoriesItem)
            End If
            If GetType(Global.LightSwitchApplication.Order_DetailsItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.Order_DetailsItem)
            End If
            If GetType(Global.LightSwitchApplication.OrdersItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.OrdersItem)
            End If
            If GetType(Global.LightSwitchApplication.ProductsItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.ProductsItem)
            End If
            If GetType(Global.LightSwitchApplication.RegionItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.RegionItem)
            End If
            If GetType(Global.LightSwitchApplication.ShippersItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.ShippersItem)
            End If
            If GetType(Global.LightSwitchApplication.SuppliersItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.SuppliersItem)
            End If
            If GetType(Global.LightSwitchApplication.TerritoriesItem).Equals(definitionType)
                Return GetType(Global.LightSwitchApplication.Implementation.TerritoriesItem)
            End If
            Return Nothing
        End Function
    End Class
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class Chofer
        Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation
        Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
     
        Private Property _ModifiedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Modified
            Get
                Return Me.Modified
            End Get
            Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
                Me.Modified = value
            End Set
        End Property
    
        Private Property _ModifiedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
            Set(ByVal value As String)
                Me.ModifiedBy = value
            End Set
        End Property
    
        Private Property _CreatedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Created
            Get
                Return Me.Created
            End Get
            Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
                Me.Created = value
            End Set
        End Property
    
        Private Property _CreatedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
            Set(ByVal value As String)
                Me.CreatedBy = value
            End Set
        End Property

        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Property _CUILImplementation() As String Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation.CUIL
            Get
                Return Me.CUIL
            End Get
            Set(ByVal value As String)
                Me.CUIL = value
            End Set
        End Property
        
        Private Property _ApellidoImplementation() As String Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation.Apellido
            Get
                Return Me.Apellido
            End Get
            Set(ByVal value As String)
                Me.Apellido = value
            End Set
        End Property
        
        Private Property _NombreImplementation() As String Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation.Nombre
            Get
                Return Me.Nombre
            End Get
            Set(ByVal value As String)
                Me.Nombre = value
            End Set
        End Property
        
        Private Property _FechaDeNacimientoImplementation() As Date Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation.FechaDeNacimiento
            Get
                Return Me.FechaDeNacimiento
            End Get
            Set(ByVal value As Date)
                Me.FechaDeNacimiento = value
            End Set
        End Property
        
        Private Property _ShippersItem_ShipperIDImplementation() As Integer Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation.ShippersItem_ShipperID
            Get
                Return Me.ShippersItem_ShipperID
            End Get
            Set(ByVal value As Integer)
                Me.ShippersItem_ShipperID = value
            End Set
        End Property
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private ReadOnly Property _ViajeCollectionImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.Chofer.DetailsClass.IImplementation.ViajeCollection
            Get
                Return Me.ViajeCollection
            End Get
        End Property
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class Viaje
        Implements Global.LightSwitchApplication.Viaje.DetailsClass.IImplementation
        Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
     
        Private Property _ModifiedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Modified
            Get
                Return Me.Modified
            End Get
            Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
                Me.Modified = value
            End Set
        End Property
    
        Private Property _ModifiedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
            Set(ByVal value As String)
                Me.ModifiedBy = value
            End Set
        End Property
    
        Private Property _CreatedPropertyImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.Created
            Get
                Return Me.Created
            End Get
            Set(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
                Me.Created = value
            End Set
        End Property
    
        Private Property _CreatedByPropertyImplementation() As String Implements Global.Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
            Set(ByVal value As String)
                Me.CreatedBy = value
            End Set
        End Property

        Private Property _IdImplementation() As Integer Implements Global.LightSwitchApplication.Viaje.DetailsClass.IImplementation.Id
            Get
                Return Me.Id
            End Get
            Set(ByVal value As Integer)
                Me.Id = value
            End Set
        End Property
        
        Private Property _FechaImplementation() As Date Implements Global.LightSwitchApplication.Viaje.DetailsClass.IImplementation.Fecha
            Get
                Return Me.Fecha
            End Get
            Set(ByVal value As Date)
                Me.Fecha = value
            End Set
        End Property
        
        Private Property _CiudadDestinoImplementation() As String Implements Global.LightSwitchApplication.Viaje.DetailsClass.IImplementation.CiudadDestino
            Get
                Return Me.CiudadDestino
            End Get
            Set(ByVal value As String)
                Me.CiudadDestino = value
            End Set
        End Property
        
        Private Property _CodigoPostalImplementation() As Integer Implements Global.LightSwitchApplication.Viaje.DetailsClass.IImplementation.CodigoPostal
            Get
                Return Me.CodigoPostal
            End Get
            Set(ByVal value As Integer)
                Me.CodigoPostal = value
            End Set
        End Property
        
        Private ReadOnly Property _CreatedByImplementation() As String Implements Global.LightSwitchApplication.Viaje.DetailsClass.IImplementation.CreatedBy
            Get
                Return Me.CreatedBy
            End Get
        End Property
        
        Private ReadOnly Property _CreatedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.Viaje.DetailsClass.IImplementation.Created
            Get
                Return Me.Created
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedByImplementation() As String Implements Global.LightSwitchApplication.Viaje.DetailsClass.IImplementation.ModifiedBy
            Get
                Return Me.ModifiedBy
            End Get
        End Property
        
        Private ReadOnly Property _ModifiedImplementation() As Global.System.Nullable(Of Global.System.DateTimeOffset) Implements Global.LightSwitchApplication.Viaje.DetailsClass.IImplementation.Modified
            Get
                Return Me.Modified
            End Get
        End Property
        
        Private Property _RowVersionImplementation() As Byte() Implements Global.LightSwitchApplication.Viaje.DetailsClass.IImplementation.RowVersion
            Get
                Return Me.RowVersion
            End Get
            Set(ByVal value As Byte())
                Me.RowVersion = value
            End Set
        End Property
        
        Private Property _ChoferImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Viaje.DetailsClass.IImplementation.Chofer
            Get
                Return Me.Chofer
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.Chofer = DirectCast(value, Global.LightSwitchApplication.Implementation.Chofer)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("Chofer")
                End If
            End Set
        End Property
        
        Private Sub OnChofer_ViajeChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("Chofer")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class CategoriesItem
        Implements Global.LightSwitchApplication.CategoriesItem.DetailsClass.IImplementation

        Private ReadOnly Property _CategoryIDImplementation() As Integer Implements Global.LightSwitchApplication.CategoriesItem.DetailsClass.IImplementation.CategoryID
            Get
                Return Me.CategoryID
            End Get
        End Property
        
        Private Property _CategoryNameImplementation() As String Implements Global.LightSwitchApplication.CategoriesItem.DetailsClass.IImplementation.CategoryName
            Get
                Return Me.CategoryName
            End Get
            Set(ByVal value As String)
                Me.CategoryName = value
            End Set
        End Property
        
        Private Property _DescriptionImplementation() As String Implements Global.LightSwitchApplication.CategoriesItem.DetailsClass.IImplementation.Description
            Get
                Return Me.Description
            End Get
            Set(ByVal value As String)
                Me.Description = value
            End Set
        End Property
        
        Private Property _PictureImplementation() As Byte() Implements Global.LightSwitchApplication.CategoriesItem.DetailsClass.IImplementation.Picture
            Get
                Return Me.Picture
            End Get
            Set(ByVal value As Byte())
                Me.Picture = value
            End Set
        End Property
        
        Private ReadOnly Property _ProductsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.CategoriesItem.DetailsClass.IImplementation.Products
            Get
                Return Me.Products
            End Get
        End Property
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class CustomerCustomerDemoItem
        Implements Global.LightSwitchApplication.CustomerCustomerDemoItem.DetailsClass.IImplementation

        Private Property _CustomerIDImplementation() As String Implements Global.LightSwitchApplication.CustomerCustomerDemoItem.DetailsClass.IImplementation.CustomerID
            Get
                Return Me.CustomerID
            End Get
            Set(ByVal value As String)
                Me.CustomerID = value
            End Set
        End Property
        
        Private Property _CustomerTypeIDImplementation() As String Implements Global.LightSwitchApplication.CustomerCustomerDemoItem.DetailsClass.IImplementation.CustomerTypeID
            Get
                Return Me.CustomerTypeID
            End Get
            Set(ByVal value As String)
                Me.CustomerTypeID = value
            End Set
        End Property
        
        Private Property _CustomerDemographicsItemImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.CustomerCustomerDemoItem.DetailsClass.IImplementation.CustomerDemographicsItem
            Get
                Return Me.CustomerDemographicsItem
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.CustomerDemographicsItem = DirectCast(value, Global.LightSwitchApplication.Implementation.CustomerDemographicsItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("CustomerDemographicsItem")
                End If
            End Set
        End Property
        
        Private Property _CustomersItemImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.CustomerCustomerDemoItem.DetailsClass.IImplementation.CustomersItem
            Get
                Return Me.CustomersItem
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.CustomersItem = DirectCast(value, Global.LightSwitchApplication.Implementation.CustomersItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("CustomersItem")
                End If
            End Set
        End Property
        
        Private Sub OnCustomerTypeIDChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("CustomerDemographicsItem")
            End If
        End Sub
        
        Private Sub OnCustomerIDChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("CustomersItem")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class CustomerDemographicsItem
        Implements Global.LightSwitchApplication.CustomerDemographicsItem.DetailsClass.IImplementation

        Private Property _CustomerTypeIDImplementation() As String Implements Global.LightSwitchApplication.CustomerDemographicsItem.DetailsClass.IImplementation.CustomerTypeID
            Get
                Return Me.CustomerTypeID
            End Get
            Set(ByVal value As String)
                Me.CustomerTypeID = value
            End Set
        End Property
        
        Private Property _CustomerDescImplementation() As String Implements Global.LightSwitchApplication.CustomerDemographicsItem.DetailsClass.IImplementation.CustomerDesc
            Get
                Return Me.CustomerDesc
            End Get
            Set(ByVal value As String)
                Me.CustomerDesc = value
            End Set
        End Property
        
        Private ReadOnly Property _CustomerCustomerDemoImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.CustomerDemographicsItem.DetailsClass.IImplementation.CustomerCustomerDemo
            Get
                Return Me.CustomerCustomerDemo
            End Get
        End Property
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class CustomersItem
        Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation

        Private Property _CustomerIDImplementation() As String Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.CustomerID
            Get
                Return Me.CustomerID
            End Get
            Set(ByVal value As String)
                Me.CustomerID = value
            End Set
        End Property
        
        Private Property _CompanyNameImplementation() As String Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.CompanyName
            Get
                Return Me.CompanyName
            End Get
            Set(ByVal value As String)
                Me.CompanyName = value
            End Set
        End Property
        
        Private Property _ContactNameImplementation() As String Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.ContactName
            Get
                Return Me.ContactName
            End Get
            Set(ByVal value As String)
                Me.ContactName = value
            End Set
        End Property
        
        Private Property _ContactTitleImplementation() As String Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.ContactTitle
            Get
                Return Me.ContactTitle
            End Get
            Set(ByVal value As String)
                Me.ContactTitle = value
            End Set
        End Property
        
        Private Property _AddressImplementation() As String Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.Address
            Get
                Return Me.Address
            End Get
            Set(ByVal value As String)
                Me.Address = value
            End Set
        End Property
        
        Private Property _CityImplementation() As String Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.City
            Get
                Return Me.City
            End Get
            Set(ByVal value As String)
                Me.City = value
            End Set
        End Property
        
        Private Property _RegionImplementation() As String Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.Region
            Get
                Return Me.Region
            End Get
            Set(ByVal value As String)
                Me.Region = value
            End Set
        End Property
        
        Private Property _PostalCodeImplementation() As String Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.PostalCode
            Get
                Return Me.PostalCode
            End Get
            Set(ByVal value As String)
                Me.PostalCode = value
            End Set
        End Property
        
        Private Property _CountryImplementation() As String Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.Country
            Get
                Return Me.Country
            End Get
            Set(ByVal value As String)
                Me.Country = value
            End Set
        End Property
        
        Private Property _PhoneImplementation() As String Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.Phone
            Get
                Return Me.Phone
            End Get
            Set(ByVal value As String)
                Me.Phone = value
            End Set
        End Property
        
        Private Property _FaxImplementation() As String Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.Fax
            Get
                Return Me.Fax
            End Get
            Set(ByVal value As String)
                Me.Fax = value
            End Set
        End Property
        
        Private ReadOnly Property _CustomerCustomerDemoImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.CustomerCustomerDemo
            Get
                Return Me.CustomerCustomerDemo
            End Get
        End Property
        
        Private ReadOnly Property _OrdersImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.CustomersItem.DetailsClass.IImplementation.Orders
            Get
                Return Me.Orders
            End Get
        End Property
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class EmployeesItem
        Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation

        Private ReadOnly Property _EmployeeIDImplementation() As Integer Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.EmployeeID
            Get
                Return Me.EmployeeID
            End Get
        End Property
        
        Private Property _LastNameImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.LastName
            Get
                Return Me.LastName
            End Get
            Set(ByVal value As String)
                Me.LastName = value
            End Set
        End Property
        
        Private Property _FirstNameImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.FirstName
            Get
                Return Me.FirstName
            End Get
            Set(ByVal value As String)
                Me.FirstName = value
            End Set
        End Property
        
        Private Property _TitleImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.Title
            Get
                Return Me.Title
            End Get
            Set(ByVal value As String)
                Me.Title = value
            End Set
        End Property
        
        Private Property _TitleOfCourtesyImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.TitleOfCourtesy
            Get
                Return Me.TitleOfCourtesy
            End Get
            Set(ByVal value As String)
                Me.TitleOfCourtesy = value
            End Set
        End Property
        
        Private Property _BirthDateImplementation() As Global.System.Nullable(Of Date) Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.BirthDate
            Get
                Return Me.BirthDate
            End Get
            Set(ByVal value As Global.System.Nullable(Of Date))
                Me.BirthDate = value
            End Set
        End Property
        
        Private Property _HireDateImplementation() As Global.System.Nullable(Of Date) Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.HireDate
            Get
                Return Me.HireDate
            End Get
            Set(ByVal value As Global.System.Nullable(Of Date))
                Me.HireDate = value
            End Set
        End Property
        
        Private Property _AddressImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.Address
            Get
                Return Me.Address
            End Get
            Set(ByVal value As String)
                Me.Address = value
            End Set
        End Property
        
        Private Property _CityImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.City
            Get
                Return Me.City
            End Get
            Set(ByVal value As String)
                Me.City = value
            End Set
        End Property
        
        Private Property _RegionImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.Region
            Get
                Return Me.Region
            End Get
            Set(ByVal value As String)
                Me.Region = value
            End Set
        End Property
        
        Private Property _PostalCodeImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.PostalCode
            Get
                Return Me.PostalCode
            End Get
            Set(ByVal value As String)
                Me.PostalCode = value
            End Set
        End Property
        
        Private Property _CountryImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.Country
            Get
                Return Me.Country
            End Get
            Set(ByVal value As String)
                Me.Country = value
            End Set
        End Property
        
        Private Property _HomePhoneImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.HomePhone
            Get
                Return Me.HomePhone
            End Get
            Set(ByVal value As String)
                Me.HomePhone = value
            End Set
        End Property
        
        Private Property _ExtensionImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.Extension
            Get
                Return Me.Extension
            End Get
            Set(ByVal value As String)
                Me.Extension = value
            End Set
        End Property
        
        Private Property _PhotoImplementation() As Byte() Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.Photo
            Get
                Return Me.Photo
            End Get
            Set(ByVal value As Byte())
                Me.Photo = value
            End Set
        End Property
        
        Private Property _NotesImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.Notes
            Get
                Return Me.Notes
            End Get
            Set(ByVal value As String)
                Me.Notes = value
            End Set
        End Property
        
        Private Property _PhotoPathImplementation() As String Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.PhotoPath
            Get
                Return Me.PhotoPath
            End Get
            Set(ByVal value As String)
                Me.PhotoPath = value
            End Set
        End Property
        
        Private ReadOnly Property _EmployeesImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.Employees
            Get
                Return Me.Employees
            End Get
        End Property
        
        Private Property _EmployeesItem1Implementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.EmployeesItem1
            Get
                Return Me.EmployeesItem1
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.EmployeesItem1 = DirectCast(value, Global.LightSwitchApplication.Implementation.EmployeesItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("EmployeesItem1")
                End If
            End Set
        End Property
        
        Private ReadOnly Property _EmployeeTerritoriesImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.EmployeeTerritories
            Get
                Return Me.EmployeeTerritories
            End Get
        End Property
        
        Private ReadOnly Property _OrdersImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.EmployeesItem.DetailsClass.IImplementation.Orders
            Get
                Return Me.Orders
            End Get
        End Property
        
        Private Sub OnReportsToChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("EmployeesItem1")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class EmployeeTerritoriesItem
        Implements Global.LightSwitchApplication.EmployeeTerritoriesItem.DetailsClass.IImplementation

        Private Property _EmployeeIDImplementation() As Integer Implements Global.LightSwitchApplication.EmployeeTerritoriesItem.DetailsClass.IImplementation.EmployeeID
            Get
                Return Me.EmployeeID
            End Get
            Set(ByVal value As Integer)
                Me.EmployeeID = value
            End Set
        End Property
        
        Private Property _TerritoryIDImplementation() As String Implements Global.LightSwitchApplication.EmployeeTerritoriesItem.DetailsClass.IImplementation.TerritoryID
            Get
                Return Me.TerritoryID
            End Get
            Set(ByVal value As String)
                Me.TerritoryID = value
            End Set
        End Property
        
        Private Property _EmployeesItemImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.EmployeeTerritoriesItem.DetailsClass.IImplementation.EmployeesItem
            Get
                Return Me.EmployeesItem
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.EmployeesItem = DirectCast(value, Global.LightSwitchApplication.Implementation.EmployeesItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("EmployeesItem")
                End If
            End Set
        End Property
        
        Private Property _TerritoriesItemImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.EmployeeTerritoriesItem.DetailsClass.IImplementation.TerritoriesItem
            Get
                Return Me.TerritoriesItem
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.TerritoriesItem = DirectCast(value, Global.LightSwitchApplication.Implementation.TerritoriesItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("TerritoriesItem")
                End If
            End Set
        End Property
        
        Private Sub OnEmployeeIDChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("EmployeesItem")
            End If
        End Sub
        
        Private Sub OnTerritoryIDChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("TerritoriesItem")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class Order_DetailsItem
        Implements Global.LightSwitchApplication.Order_DetailsItem.DetailsClass.IImplementation

        Private Property _OrderIDImplementation() As Integer Implements Global.LightSwitchApplication.Order_DetailsItem.DetailsClass.IImplementation.OrderID
            Get
                Return Me.OrderID
            End Get
            Set(ByVal value As Integer)
                Me.OrderID = value
            End Set
        End Property
        
        Private Property _ProductIDImplementation() As Integer Implements Global.LightSwitchApplication.Order_DetailsItem.DetailsClass.IImplementation.ProductID
            Get
                Return Me.ProductID
            End Get
            Set(ByVal value As Integer)
                Me.ProductID = value
            End Set
        End Property
        
        Private Property _UnitPriceImplementation() As Decimal Implements Global.LightSwitchApplication.Order_DetailsItem.DetailsClass.IImplementation.UnitPrice
            Get
                Return Me.UnitPrice
            End Get
            Set(ByVal value As Decimal)
                Me.UnitPrice = value
            End Set
        End Property
        
        Private Property _QuantityImplementation() As Short Implements Global.LightSwitchApplication.Order_DetailsItem.DetailsClass.IImplementation.Quantity
            Get
                Return Me.Quantity
            End Get
            Set(ByVal value As Short)
                Me.Quantity = value
            End Set
        End Property
        
        Private Property _DiscountImplementation() As Single Implements Global.LightSwitchApplication.Order_DetailsItem.DetailsClass.IImplementation.Discount
            Get
                Return Me.Discount
            End Get
            Set(ByVal value As Single)
                Me.Discount = value
            End Set
        End Property
        
        Private Property _OrdersItemImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Order_DetailsItem.DetailsClass.IImplementation.OrdersItem
            Get
                Return Me.OrdersItem
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.OrdersItem = DirectCast(value, Global.LightSwitchApplication.Implementation.OrdersItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("OrdersItem")
                End If
            End Set
        End Property
        
        Private Property _ProductsItemImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.Order_DetailsItem.DetailsClass.IImplementation.ProductsItem
            Get
                Return Me.ProductsItem
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.ProductsItem = DirectCast(value, Global.LightSwitchApplication.Implementation.ProductsItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("ProductsItem")
                End If
            End Set
        End Property
        
        Private Sub OnOrderIDChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("OrdersItem")
            End If
        End Sub
        
        Private Sub OnProductIDChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("ProductsItem")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class OrdersItem
        Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation

        Private ReadOnly Property _OrderIDImplementation() As Integer Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.OrderID
            Get
                Return Me.OrderID
            End Get
        End Property
        
        Private Property _OrderDateImplementation() As Global.System.Nullable(Of Date) Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.OrderDate
            Get
                Return Me.OrderDate
            End Get
            Set(ByVal value As Global.System.Nullable(Of Date))
                Me.OrderDate = value
            End Set
        End Property
        
        Private Property _RequiredDateImplementation() As Global.System.Nullable(Of Date) Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.RequiredDate
            Get
                Return Me.RequiredDate
            End Get
            Set(ByVal value As Global.System.Nullable(Of Date))
                Me.RequiredDate = value
            End Set
        End Property
        
        Private Property _ShippedDateImplementation() As Global.System.Nullable(Of Date) Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.ShippedDate
            Get
                Return Me.ShippedDate
            End Get
            Set(ByVal value As Global.System.Nullable(Of Date))
                Me.ShippedDate = value
            End Set
        End Property
        
        Private Property _FreightImplementation() As Global.System.Nullable(Of Decimal) Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.Freight
            Get
                Return Me.Freight
            End Get
            Set(ByVal value As Global.System.Nullable(Of Decimal))
                Me.Freight = value
            End Set
        End Property
        
        Private Property _ShipNameImplementation() As String Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.ShipName
            Get
                Return Me.ShipName
            End Get
            Set(ByVal value As String)
                Me.ShipName = value
            End Set
        End Property
        
        Private Property _ShipAddressImplementation() As String Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.ShipAddress
            Get
                Return Me.ShipAddress
            End Get
            Set(ByVal value As String)
                Me.ShipAddress = value
            End Set
        End Property
        
        Private Property _ShipCityImplementation() As String Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.ShipCity
            Get
                Return Me.ShipCity
            End Get
            Set(ByVal value As String)
                Me.ShipCity = value
            End Set
        End Property
        
        Private Property _ShipRegionImplementation() As String Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.ShipRegion
            Get
                Return Me.ShipRegion
            End Get
            Set(ByVal value As String)
                Me.ShipRegion = value
            End Set
        End Property
        
        Private Property _ShipPostalCodeImplementation() As String Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.ShipPostalCode
            Get
                Return Me.ShipPostalCode
            End Get
            Set(ByVal value As String)
                Me.ShipPostalCode = value
            End Set
        End Property
        
        Private Property _ShipCountryImplementation() As String Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.ShipCountry
            Get
                Return Me.ShipCountry
            End Get
            Set(ByVal value As String)
                Me.ShipCountry = value
            End Set
        End Property
        
        Private ReadOnly Property _Order_DetailsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.Order_Details
            Get
                Return Me.Order_Details
            End Get
        End Property
        
        Private Property _CustomersItemImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.CustomersItem
            Get
                Return Me.CustomersItem
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.CustomersItem = DirectCast(value, Global.LightSwitchApplication.Implementation.CustomersItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("CustomersItem")
                End If
            End Set
        End Property
        
        Private Property _EmployeesItemImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.EmployeesItem
            Get
                Return Me.EmployeesItem
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.EmployeesItem = DirectCast(value, Global.LightSwitchApplication.Implementation.EmployeesItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("EmployeesItem")
                End If
            End Set
        End Property
        
        Private Property _ShippersItemImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.OrdersItem.DetailsClass.IImplementation.ShippersItem
            Get
                Return Me.ShippersItem
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.ShippersItem = DirectCast(value, Global.LightSwitchApplication.Implementation.ShippersItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("ShippersItem")
                End If
            End Set
        End Property
        
        Private Sub OnCustomerIDChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("CustomersItem")
            End If
        End Sub
        
        Private Sub OnEmployeeIDChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("EmployeesItem")
            End If
        End Sub
        
        Private Sub OnShipViaChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("ShippersItem")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class ProductsItem
        Implements Global.LightSwitchApplication.ProductsItem.DetailsClass.IImplementation

        Private ReadOnly Property _ProductIDImplementation() As Integer Implements Global.LightSwitchApplication.ProductsItem.DetailsClass.IImplementation.ProductID
            Get
                Return Me.ProductID
            End Get
        End Property
        
        Private Property _ProductNameImplementation() As String Implements Global.LightSwitchApplication.ProductsItem.DetailsClass.IImplementation.ProductName
            Get
                Return Me.ProductName
            End Get
            Set(ByVal value As String)
                Me.ProductName = value
            End Set
        End Property
        
        Private Property _QuantityPerUnitImplementation() As String Implements Global.LightSwitchApplication.ProductsItem.DetailsClass.IImplementation.QuantityPerUnit
            Get
                Return Me.QuantityPerUnit
            End Get
            Set(ByVal value As String)
                Me.QuantityPerUnit = value
            End Set
        End Property
        
        Private Property _UnitPriceImplementation() As Global.System.Nullable(Of Decimal) Implements Global.LightSwitchApplication.ProductsItem.DetailsClass.IImplementation.UnitPrice
            Get
                Return Me.UnitPrice
            End Get
            Set(ByVal value As Global.System.Nullable(Of Decimal))
                Me.UnitPrice = value
            End Set
        End Property
        
        Private Property _UnitsInStockImplementation() As Global.System.Nullable(Of Short) Implements Global.LightSwitchApplication.ProductsItem.DetailsClass.IImplementation.UnitsInStock
            Get
                Return Me.UnitsInStock
            End Get
            Set(ByVal value As Global.System.Nullable(Of Short))
                Me.UnitsInStock = value
            End Set
        End Property
        
        Private Property _UnitsOnOrderImplementation() As Global.System.Nullable(Of Short) Implements Global.LightSwitchApplication.ProductsItem.DetailsClass.IImplementation.UnitsOnOrder
            Get
                Return Me.UnitsOnOrder
            End Get
            Set(ByVal value As Global.System.Nullable(Of Short))
                Me.UnitsOnOrder = value
            End Set
        End Property
        
        Private Property _ReorderLevelImplementation() As Global.System.Nullable(Of Short) Implements Global.LightSwitchApplication.ProductsItem.DetailsClass.IImplementation.ReorderLevel
            Get
                Return Me.ReorderLevel
            End Get
            Set(ByVal value As Global.System.Nullable(Of Short))
                Me.ReorderLevel = value
            End Set
        End Property
        
        Private Property _DiscontinuedImplementation() As Boolean Implements Global.LightSwitchApplication.ProductsItem.DetailsClass.IImplementation.Discontinued
            Get
                Return Me.Discontinued
            End Get
            Set(ByVal value As Boolean)
                Me.Discontinued = value
            End Set
        End Property
        
        Private ReadOnly Property _Order_DetailsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.ProductsItem.DetailsClass.IImplementation.Order_Details
            Get
                Return Me.Order_Details
            End Get
        End Property
        
        Private Property _CategoriesItemImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.ProductsItem.DetailsClass.IImplementation.CategoriesItem
            Get
                Return Me.CategoriesItem
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.CategoriesItem = DirectCast(value, Global.LightSwitchApplication.Implementation.CategoriesItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("CategoriesItem")
                End If
            End Set
        End Property
        
        Private Property _SuppliersItemImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.ProductsItem.DetailsClass.IImplementation.SuppliersItem
            Get
                Return Me.SuppliersItem
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.SuppliersItem = DirectCast(value, Global.LightSwitchApplication.Implementation.SuppliersItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("SuppliersItem")
                End If
            End Set
        End Property
        
        Private Sub OnCategoryIDChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("CategoriesItem")
            End If
        End Sub
        
        Private Sub OnSupplierIDChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("SuppliersItem")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class RegionItem
        Implements Global.LightSwitchApplication.RegionItem.DetailsClass.IImplementation

        Private Property _RegionIDImplementation() As Integer Implements Global.LightSwitchApplication.RegionItem.DetailsClass.IImplementation.RegionID
            Get
                Return Me.RegionID
            End Get
            Set(ByVal value As Integer)
                Me.RegionID = value
            End Set
        End Property
        
        Private Property _RegionDescriptionImplementation() As String Implements Global.LightSwitchApplication.RegionItem.DetailsClass.IImplementation.RegionDescription
            Get
                Return Me.RegionDescription
            End Get
            Set(ByVal value As String)
                Me.RegionDescription = value
            End Set
        End Property
        
        Private ReadOnly Property _TerritoriesImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.RegionItem.DetailsClass.IImplementation.Territories
            Get
                Return Me.Territories
            End Get
        End Property
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class ShippersItem
        Implements Global.LightSwitchApplication.ShippersItem.DetailsClass.IImplementation

        Private ReadOnly Property _ShipperIDImplementation() As Integer Implements Global.LightSwitchApplication.ShippersItem.DetailsClass.IImplementation.ShipperID
            Get
                Return Me.ShipperID
            End Get
        End Property
        
        Private Property _CompanyNameImplementation() As String Implements Global.LightSwitchApplication.ShippersItem.DetailsClass.IImplementation.CompanyName
            Get
                Return Me.CompanyName
            End Get
            Set(ByVal value As String)
                Me.CompanyName = value
            End Set
        End Property
        
        Private Property _PhoneImplementation() As String Implements Global.LightSwitchApplication.ShippersItem.DetailsClass.IImplementation.Phone
            Get
                Return Me.Phone
            End Get
            Set(ByVal value As String)
                Me.Phone = value
            End Set
        End Property
        
        Private ReadOnly Property _OrdersImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.ShippersItem.DetailsClass.IImplementation.Orders
            Get
                Return Me.Orders
            End Get
        End Property
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class SuppliersItem
        Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation

        Private ReadOnly Property _SupplierIDImplementation() As Integer Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.SupplierID
            Get
                Return Me.SupplierID
            End Get
        End Property
        
        Private Property _CompanyNameImplementation() As String Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.CompanyName
            Get
                Return Me.CompanyName
            End Get
            Set(ByVal value As String)
                Me.CompanyName = value
            End Set
        End Property
        
        Private Property _ContactNameImplementation() As String Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.ContactName
            Get
                Return Me.ContactName
            End Get
            Set(ByVal value As String)
                Me.ContactName = value
            End Set
        End Property
        
        Private Property _ContactTitleImplementation() As String Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.ContactTitle
            Get
                Return Me.ContactTitle
            End Get
            Set(ByVal value As String)
                Me.ContactTitle = value
            End Set
        End Property
        
        Private Property _AddressImplementation() As String Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.Address
            Get
                Return Me.Address
            End Get
            Set(ByVal value As String)
                Me.Address = value
            End Set
        End Property
        
        Private Property _CityImplementation() As String Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.City
            Get
                Return Me.City
            End Get
            Set(ByVal value As String)
                Me.City = value
            End Set
        End Property
        
        Private Property _RegionImplementation() As String Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.Region
            Get
                Return Me.Region
            End Get
            Set(ByVal value As String)
                Me.Region = value
            End Set
        End Property
        
        Private Property _PostalCodeImplementation() As String Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.PostalCode
            Get
                Return Me.PostalCode
            End Get
            Set(ByVal value As String)
                Me.PostalCode = value
            End Set
        End Property
        
        Private Property _CountryImplementation() As String Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.Country
            Get
                Return Me.Country
            End Get
            Set(ByVal value As String)
                Me.Country = value
            End Set
        End Property
        
        Private Property _PhoneImplementation() As String Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.Phone
            Get
                Return Me.Phone
            End Get
            Set(ByVal value As String)
                Me.Phone = value
            End Set
        End Property
        
        Private Property _FaxImplementation() As String Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.Fax
            Get
                Return Me.Fax
            End Get
            Set(ByVal value As String)
                Me.Fax = value
            End Set
        End Property
        
        Private Property _HomePageImplementation() As String Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.HomePage
            Get
                Return Me.HomePage
            End Get
            Set(ByVal value As String)
                Me.HomePage = value
            End Set
        End Property
        
        Private ReadOnly Property _ProductsImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.SuppliersItem.DetailsClass.IImplementation.Products
            Get
                Return Me.Products
            End Get
        End Property
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Partial Public Class TerritoriesItem
        Implements Global.LightSwitchApplication.TerritoriesItem.DetailsClass.IImplementation

        Private Property _TerritoryIDImplementation() As String Implements Global.LightSwitchApplication.TerritoriesItem.DetailsClass.IImplementation.TerritoryID
            Get
                Return Me.TerritoryID
            End Get
            Set(ByVal value As String)
                Me.TerritoryID = value
            End Set
        End Property
        
        Private Property _TerritoryDescriptionImplementation() As String Implements Global.LightSwitchApplication.TerritoriesItem.DetailsClass.IImplementation.TerritoryDescription
            Get
                Return Me.TerritoryDescription
            End Get
            Set(ByVal value As String)
                Me.TerritoryDescription = value
            End Set
        End Property
        
        Private ReadOnly Property _EmployeeTerritoriesImplementation() As Global.System.Collections.IEnumerable Implements Global.LightSwitchApplication.TerritoriesItem.DetailsClass.IImplementation.EmployeeTerritories
            Get
                Return Me.EmployeeTerritories
            End Get
        End Property
        
        Private Property _RegionItemImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementation Implements Global.LightSwitchApplication.TerritoriesItem.DetailsClass.IImplementation.RegionItem
            Get
                Return Me.RegionItem
            End Get
            Set(ByVal value As Global.Microsoft.LightSwitch.Internal.IEntityImplementation)
                Me.RegionItem = DirectCast(value, Global.LightSwitchApplication.Implementation.RegionItem)
                If Me.__host IsNot Nothing Then
                    Me.__host.RaisePropertyChanged("RegionItem")
                End If
            End Set
        End Property
        
        Private Sub OnRegionIDChanged()
            If Me.__host IsNot Nothing Then
                Me.__host.RaisePropertyChanged("RegionItem")
            End If
        End Sub
        
        #Region "IEntityImplementation Members"
        Private __host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost
        
        Private ReadOnly Property __HostImplementation() As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Host
            Get
                Return Me.__host
            End Get
        End Property
        
        Private Sub _Initialize(ByVal host As Global.Microsoft.LightSwitch.Internal.IEntityImplementationHost) Implements Global.Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize
            Me.__host = host
        End Sub
        
        Protected Overrides Sub OnPropertyChanged(ByVal propertyName As String)
            MyBase.OnPropertyChanged(propertyName)
        
            If Not Me.__host Is Nothing Then
                Me.__host.RaisePropertyChanged(propertyName)
            End If
        End Sub
        #End Region
    End Class
    
End Namespace

