
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __CustomersItem = LightSwitchApplication.CustomersItem

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No hay ninguna descripción modelada
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Public NotInheritable Partial Class CustomersItem
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __CustomersItem, __CustomersItem.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Inicializa una nueva instancia de la entidad CustomersItem.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __CustomersItem))
            MyBase.New(entitySet)
            
            __CustomersItem.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomersItem_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomersItem_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return TryCast(Global.LightSwitchApplication.Application.Current, Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace))
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CustomerID As String
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.CustomerID)
            End Get
            Set
                __CustomersItem.DetailsClass.SetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.CustomerID, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerID_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CompanyName As String
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.CompanyName)
            End Get
            Set
                __CustomersItem.DetailsClass.SetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.CompanyName, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CompanyName_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CompanyName_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CompanyName_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ContactName As String
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.ContactName)
            End Get
            Set
                __CustomersItem.DetailsClass.SetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.ContactName, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ContactName_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ContactName_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ContactName_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property ContactTitle As String
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.ContactTitle)
            End Get
            Set
                __CustomersItem.DetailsClass.SetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.ContactTitle, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ContactTitle_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ContactTitle_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ContactTitle_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Address As String
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.Address)
            End Get
            Set
                __CustomersItem.DetailsClass.SetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.Address, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property City As String
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.City)
            End Get
            Set
                __CustomersItem.DetailsClass.SetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.City, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub City_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub City_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub City_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Region As String
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.Region)
            End Get
            Set
                __CustomersItem.DetailsClass.SetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.Region, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Region_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Region_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Region_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property PostalCode As String
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.PostalCode)
            End Get
            Set
                __CustomersItem.DetailsClass.SetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.PostalCode, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PostalCode_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PostalCode_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PostalCode_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Country As String
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.Country)
            End Get
            Set
                __CustomersItem.DetailsClass.SetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.Country, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Country_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Country_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Country_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Phone As String
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.Phone)
            End Get
            Set
                __CustomersItem.DetailsClass.SetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.Phone, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Fax As String
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.Fax)
            End Get
            Set
                __CustomersItem.DetailsClass.SetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.Fax, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Fax_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Fax_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Fax_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property CustomerCustomerDemo As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.CustomerCustomerDemoItem)
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.CustomerCustomerDemo)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property CustomerCustomerDemoQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.CustomerCustomerDemoItem)
            Get
                Return __CustomersItem.DetailsClass.GetQuery(Me, __CustomersItem.DetailsClass.PropertySetProperties.CustomerCustomerDemo)
            End Get
        End Property

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Orders As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.OrdersItem)
            Get
                Return __CustomersItem.DetailsClass.GetValue(Me, __CustomersItem.DetailsClass.PropertySetProperties.Orders)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property OrdersQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.OrdersItem)
            Get
                Return __CustomersItem.DetailsClass.GetQuery(Me, __CustomersItem.DetailsClass.PropertySetProperties.Orders)
            End Get
        End Property

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __CustomersItem, _
                __CustomersItem.DetailsClass, _
                __CustomersItem.DetailsClass.IImplementation, _
                __CustomersItem.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __CustomersItem, __CustomersItem.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __CustomersItem, __CustomersItem.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __CustomersItem.DetailsClass.PropertySetProperties.CustomerID
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __CustomersItemEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __CustomersItem, __CustomersItem.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __CustomersItem, __CustomersItem.DetailsClass).Entry( _
                    AddressOf __CustomersItem.DetailsClass.__CustomersItem_CreateNew, _
                    AddressOf __CustomersItem.DetailsClass.__CustomersItem_Created, _
                    AddressOf __CustomersItem.DetailsClass.__CustomersItem_AllowSaveWithErrors)
            Private Shared Function __CustomersItem_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __CustomersItem)) As __CustomersItem
                Return New __CustomersItem(es)
            End Function
            Private Shared Sub __CustomersItem_Created(e As __CustomersItem)
                e.CustomersItem_Created()
            End Sub
            Private Shared Function __CustomersItem_AllowSaveWithErrors(e As __CustomersItem) As Boolean
                Dim result As Boolean = False
                e.CustomersItem_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __CustomersItem, __CustomersItem.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __CustomersItem, __CustomersItem.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __CustomersItem.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __CustomersItem, __CustomersItem.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property CustomerID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.CustomerID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property CompanyName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.CompanyName),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property ContactName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.ContactName),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property ContactTitle As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.ContactTitle),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Address As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.Address),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property City As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.City),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Region As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.Region),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property PostalCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.PostalCode),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Country As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.Country),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Phone As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.Phone),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Fax As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.Fax),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property CustomerCustomerDemo As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomersItem, __CustomersItem.DetailsClass, Global.LightSwitchApplication.CustomerCustomerDemoItem)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.CustomerCustomerDemo),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomersItem, __CustomersItem.DetailsClass, Global.LightSwitchApplication.CustomerCustomerDemoItem))
                    End Get
                End Property
                
                Public ReadOnly Property Orders As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomersItem, __CustomersItem.DetailsClass, Global.LightSwitchApplication.OrdersItem)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomersItem.DetailsClass.PropertySetProperties.Orders),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomersItem, __CustomersItem.DetailsClass, Global.LightSwitchApplication.OrdersItem))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property CustomerID As String
                Shadows Property CompanyName As String
                Shadows Property ContactName As String
                Shadows Property ContactTitle As String
                Shadows Property Address As String
                Shadows Property City As String
                Shadows Property Region As String
                Shadows Property PostalCode As String
                Shadows Property Country As String
                Shadows Property Phone As String
                Shadows Property Fax As String
                Shadows ReadOnly Property CustomerCustomerDemo As Global.System.Collections.IEnumerable
                Shadows ReadOnly Property Orders As Global.System.Collections.IEnumerable
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CustomerID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry( _
                        "CustomerID", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CustomerID_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CustomerID_ComputeIsReadOnly, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CustomerID_Validate, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CustomerID_GetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CustomerID_SetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CustomerID_OnValueChanged)
                Private Shared Sub _CustomerID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._CustomerID, sf)
                End Sub
                Private Shared Function _CustomerID_ComputeIsReadOnly(e As __CustomersItem) As Boolean
                    Dim result As Boolean = False
                    e.CustomerID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CustomerID_Validate(e As __CustomersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CustomerID_Validate(r)
                End Sub
                Private Shared Function _CustomerID_GetImplementationValue(d As __CustomersItem.DetailsClass) As String
                    Return d.ImplementationEntity.CustomerID
                End Function
                Private Shared Sub _CustomerID_SetImplementationValue(d As __CustomersItem.DetailsClass, v As String)
                    d.ImplementationEntity.CustomerID = v
                End Sub
                Private Shared Sub _CustomerID_OnValueChanged(e As __CustomersItem)
                    e.CustomerID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CompanyName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry( _
                        "CompanyName", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CompanyName_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CompanyName_ComputeIsReadOnly, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CompanyName_Validate, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CompanyName_GetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CompanyName_SetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CompanyName_OnValueChanged)
                Private Shared Sub _CompanyName_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._CompanyName, sf)
                End Sub
                Private Shared Function _CompanyName_ComputeIsReadOnly(e As __CustomersItem) As Boolean
                    Dim result As Boolean = False
                    e.CompanyName_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CompanyName_Validate(e As __CustomersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CompanyName_Validate(r)
                End Sub
                Private Shared Function _CompanyName_GetImplementationValue(d As __CustomersItem.DetailsClass) As String
                    Return d.ImplementationEntity.CompanyName
                End Function
                Private Shared Sub _CompanyName_SetImplementationValue(d As __CustomersItem.DetailsClass, v As String)
                    d.ImplementationEntity.CompanyName = v
                End Sub
                Private Shared Sub _CompanyName_OnValueChanged(e As __CustomersItem)
                    e.CompanyName_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ContactName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry( _
                        "ContactName", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._ContactName_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._ContactName_ComputeIsReadOnly, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._ContactName_Validate, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._ContactName_GetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._ContactName_SetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._ContactName_OnValueChanged)
                Private Shared Sub _ContactName_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._ContactName, sf)
                End Sub
                Private Shared Function _ContactName_ComputeIsReadOnly(e As __CustomersItem) As Boolean
                    Dim result As Boolean = False
                    e.ContactName_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ContactName_Validate(e As __CustomersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ContactName_Validate(r)
                End Sub
                Private Shared Function _ContactName_GetImplementationValue(d As __CustomersItem.DetailsClass) As String
                    Return d.ImplementationEntity.ContactName
                End Function
                Private Shared Sub _ContactName_SetImplementationValue(d As __CustomersItem.DetailsClass, v As String)
                    d.ImplementationEntity.ContactName = v
                End Sub
                Private Shared Sub _ContactName_OnValueChanged(e As __CustomersItem)
                    e.ContactName_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ContactTitle As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry( _
                        "ContactTitle", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._ContactTitle_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._ContactTitle_ComputeIsReadOnly, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._ContactTitle_Validate, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._ContactTitle_GetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._ContactTitle_SetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._ContactTitle_OnValueChanged)
                Private Shared Sub _ContactTitle_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._ContactTitle, sf)
                End Sub
                Private Shared Function _ContactTitle_ComputeIsReadOnly(e As __CustomersItem) As Boolean
                    Dim result As Boolean = False
                    e.ContactTitle_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ContactTitle_Validate(e As __CustomersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ContactTitle_Validate(r)
                End Sub
                Private Shared Function _ContactTitle_GetImplementationValue(d As __CustomersItem.DetailsClass) As String
                    Return d.ImplementationEntity.ContactTitle
                End Function
                Private Shared Sub _ContactTitle_SetImplementationValue(d As __CustomersItem.DetailsClass, v As String)
                    d.ImplementationEntity.ContactTitle = v
                End Sub
                Private Shared Sub _ContactTitle_OnValueChanged(e As __CustomersItem)
                    e.ContactTitle_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Address As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry( _
                        "Address", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Address_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Address_ComputeIsReadOnly, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Address_Validate, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Address_GetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Address_SetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Address_OnValueChanged)
                Private Shared Sub _Address_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._Address, sf)
                End Sub
                Private Shared Function _Address_ComputeIsReadOnly(e As __CustomersItem) As Boolean
                    Dim result As Boolean = False
                    e.Address_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Address_Validate(e As __CustomersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Address_Validate(r)
                End Sub
                Private Shared Function _Address_GetImplementationValue(d As __CustomersItem.DetailsClass) As String
                    Return d.ImplementationEntity.Address
                End Function
                Private Shared Sub _Address_SetImplementationValue(d As __CustomersItem.DetailsClass, v As String)
                    d.ImplementationEntity.Address = v
                End Sub
                Private Shared Sub _Address_OnValueChanged(e As __CustomersItem)
                    e.Address_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly City As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry( _
                        "City", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._City_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._City_ComputeIsReadOnly, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._City_Validate, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._City_GetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._City_SetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._City_OnValueChanged)
                Private Shared Sub _City_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._City, sf)
                End Sub
                Private Shared Function _City_ComputeIsReadOnly(e As __CustomersItem) As Boolean
                    Dim result As Boolean = False
                    e.City_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _City_Validate(e As __CustomersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.City_Validate(r)
                End Sub
                Private Shared Function _City_GetImplementationValue(d As __CustomersItem.DetailsClass) As String
                    Return d.ImplementationEntity.City
                End Function
                Private Shared Sub _City_SetImplementationValue(d As __CustomersItem.DetailsClass, v As String)
                    d.ImplementationEntity.City = v
                End Sub
                Private Shared Sub _City_OnValueChanged(e As __CustomersItem)
                    e.City_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Region As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry( _
                        "Region", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Region_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Region_ComputeIsReadOnly, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Region_Validate, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Region_GetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Region_SetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Region_OnValueChanged)
                Private Shared Sub _Region_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._Region, sf)
                End Sub
                Private Shared Function _Region_ComputeIsReadOnly(e As __CustomersItem) As Boolean
                    Dim result As Boolean = False
                    e.Region_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Region_Validate(e As __CustomersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Region_Validate(r)
                End Sub
                Private Shared Function _Region_GetImplementationValue(d As __CustomersItem.DetailsClass) As String
                    Return d.ImplementationEntity.Region
                End Function
                Private Shared Sub _Region_SetImplementationValue(d As __CustomersItem.DetailsClass, v As String)
                    d.ImplementationEntity.Region = v
                End Sub
                Private Shared Sub _Region_OnValueChanged(e As __CustomersItem)
                    e.Region_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly PostalCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry( _
                        "PostalCode", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._PostalCode_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._PostalCode_ComputeIsReadOnly, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._PostalCode_Validate, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._PostalCode_GetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._PostalCode_SetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._PostalCode_OnValueChanged)
                Private Shared Sub _PostalCode_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._PostalCode, sf)
                End Sub
                Private Shared Function _PostalCode_ComputeIsReadOnly(e As __CustomersItem) As Boolean
                    Dim result As Boolean = False
                    e.PostalCode_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _PostalCode_Validate(e As __CustomersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.PostalCode_Validate(r)
                End Sub
                Private Shared Function _PostalCode_GetImplementationValue(d As __CustomersItem.DetailsClass) As String
                    Return d.ImplementationEntity.PostalCode
                End Function
                Private Shared Sub _PostalCode_SetImplementationValue(d As __CustomersItem.DetailsClass, v As String)
                    d.ImplementationEntity.PostalCode = v
                End Sub
                Private Shared Sub _PostalCode_OnValueChanged(e As __CustomersItem)
                    e.PostalCode_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Country As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry( _
                        "Country", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Country_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Country_ComputeIsReadOnly, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Country_Validate, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Country_GetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Country_SetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Country_OnValueChanged)
                Private Shared Sub _Country_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._Country, sf)
                End Sub
                Private Shared Function _Country_ComputeIsReadOnly(e As __CustomersItem) As Boolean
                    Dim result As Boolean = False
                    e.Country_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Country_Validate(e As __CustomersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Country_Validate(r)
                End Sub
                Private Shared Function _Country_GetImplementationValue(d As __CustomersItem.DetailsClass) As String
                    Return d.ImplementationEntity.Country
                End Function
                Private Shared Sub _Country_SetImplementationValue(d As __CustomersItem.DetailsClass, v As String)
                    d.ImplementationEntity.Country = v
                End Sub
                Private Shared Sub _Country_OnValueChanged(e As __CustomersItem)
                    e.Country_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Phone As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry( _
                        "Phone", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Phone_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Phone_ComputeIsReadOnly, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Phone_Validate, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Phone_GetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Phone_SetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Phone_OnValueChanged)
                Private Shared Sub _Phone_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._Phone, sf)
                End Sub
                Private Shared Function _Phone_ComputeIsReadOnly(e As __CustomersItem) As Boolean
                    Dim result As Boolean = False
                    e.Phone_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Phone_Validate(e As __CustomersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Phone_Validate(r)
                End Sub
                Private Shared Function _Phone_GetImplementationValue(d As __CustomersItem.DetailsClass) As String
                    Return d.ImplementationEntity.Phone
                End Function
                Private Shared Sub _Phone_SetImplementationValue(d As __CustomersItem.DetailsClass, v As String)
                    d.ImplementationEntity.Phone = v
                End Sub
                Private Shared Sub _Phone_OnValueChanged(e As __CustomersItem)
                    e.Phone_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Fax As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Entry( _
                        "Fax", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Fax_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Fax_ComputeIsReadOnly, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Fax_Validate, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Fax_GetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Fax_SetImplementationValue, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Fax_OnValueChanged)
                Private Shared Sub _Fax_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._Fax, sf)
                End Sub
                Private Shared Function _Fax_ComputeIsReadOnly(e As __CustomersItem) As Boolean
                    Dim result As Boolean = False
                    e.Fax_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Fax_Validate(e As __CustomersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Fax_Validate(r)
                End Sub
                Private Shared Function _Fax_GetImplementationValue(d As __CustomersItem.DetailsClass) As String
                    Return d.ImplementationEntity.Fax
                End Function
                Private Shared Sub _Fax_SetImplementationValue(d As __CustomersItem.DetailsClass, v As String)
                    d.ImplementationEntity.Fax = v
                End Sub
                Private Shared Sub _Fax_OnValueChanged(e As __CustomersItem)
                    e.Fax_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CustomerCustomerDemo As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomersItem, __CustomersItem.DetailsClass, Global.LightSwitchApplication.CustomerCustomerDemoItem).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomersItem, __CustomersItem.DetailsClass, Global.LightSwitchApplication.CustomerCustomerDemoItem).Entry( _
                        "CustomerCustomerDemo", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CustomerCustomerDemo_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CustomerCustomerDemo_GetReferencedEntities, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._CustomerCustomerDemo_GetEntityCollection)
                Private Shared Sub _CustomerCustomerDemo_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomersItem, __CustomersItem.DetailsClass, Global.LightSwitchApplication.CustomerCustomerDemoItem).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._CustomerCustomerDemo, sf)
                End Sub
                Private Shared Function _CustomerCustomerDemo_GetReferencedEntities(d As __CustomersItem.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.CustomerCustomerDemoItem)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.CustomerCustomerDemoItem, Global.LightSwitchApplication.CustomerCustomerDemoItem.DetailsClass)(__CustomersItem.DetailsClass.PropertySetProperties.CustomerCustomerDemo, d._CustomerCustomerDemo)
                End Function
                Private Shared Function _CustomerCustomerDemo_GetEntityCollection(d As __CustomersItem.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.CustomerCustomerDemo
                End Function
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Orders As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomersItem, __CustomersItem.DetailsClass, Global.LightSwitchApplication.OrdersItem).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomersItem, __CustomersItem.DetailsClass, Global.LightSwitchApplication.OrdersItem).Entry( _
                        "Orders", _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Orders_Stub, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Orders_GetReferencedEntities, _
                        AddressOf __CustomersItem.DetailsClass.PropertySetProperties._Orders_GetEntityCollection)
                Private Shared Sub _Orders_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomersItem, __CustomersItem.DetailsClass, Global.LightSwitchApplication.OrdersItem).Data), d As __CustomersItem.DetailsClass, sf As Object)
                    c(d, d._Orders, sf)
                End Sub
                Private Shared Function _Orders_GetReferencedEntities(d As __CustomersItem.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.OrdersItem)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.OrdersItem, Global.LightSwitchApplication.OrdersItem.DetailsClass)(__CustomersItem.DetailsClass.PropertySetProperties.Orders, d._Orders)
                End Function
                Private Shared Function _Orders_GetEntityCollection(d As __CustomersItem.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Orders
                End Function
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CustomerID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CompanyName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ContactName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ContactTitle As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Address As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _City As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Region As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _PostalCode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Country As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Phone As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Fax As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomersItem, __CustomersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CustomerCustomerDemo As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomersItem, __CustomersItem.DetailsClass, Global.LightSwitchApplication.CustomerCustomerDemoItem).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Orders As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomersItem, __CustomersItem.DetailsClass, Global.LightSwitchApplication.OrdersItem).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
