
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __CustomerDemographicsItem = LightSwitchApplication.CustomerDemographicsItem

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No hay ninguna descripción modelada
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Public NotInheritable Partial Class CustomerDemographicsItem
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Inicializa una nueva instancia de la entidad CustomerDemographicsItem.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __CustomerDemographicsItem))
            MyBase.New(entitySet)
            
            __CustomerDemographicsItem.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerDemographicsItem_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerDemographicsItem_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return TryCast(Global.LightSwitchApplication.Application.Current, Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace))
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CustomerTypeID As String
            Get
                Return __CustomerDemographicsItem.DetailsClass.GetValue(Me, __CustomerDemographicsItem.DetailsClass.PropertySetProperties.CustomerTypeID)
            End Get
            Set
                __CustomerDemographicsItem.DetailsClass.SetValue(Me, __CustomerDemographicsItem.DetailsClass.PropertySetProperties.CustomerTypeID, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerTypeID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerTypeID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerTypeID_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CustomerDesc As String
            Get
                Return __CustomerDemographicsItem.DetailsClass.GetValue(Me, __CustomerDemographicsItem.DetailsClass.PropertySetProperties.CustomerDesc)
            End Get
            Set
                __CustomerDemographicsItem.DetailsClass.SetValue(Me, __CustomerDemographicsItem.DetailsClass.PropertySetProperties.CustomerDesc, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerDesc_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerDesc_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CustomerDesc_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property CustomerCustomerDemo As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.CustomerCustomerDemoItem)
            Get
                Return __CustomerDemographicsItem.DetailsClass.GetValue(Me, __CustomerDemographicsItem.DetailsClass.PropertySetProperties.CustomerCustomerDemo)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property CustomerCustomerDemoQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.CustomerCustomerDemoItem)
            Get
                Return __CustomerDemographicsItem.DetailsClass.GetQuery(Me, __CustomerDemographicsItem.DetailsClass.PropertySetProperties.CustomerCustomerDemo)
            End Get
        End Property

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __CustomerDemographicsItem, _
                __CustomerDemographicsItem.DetailsClass, _
                __CustomerDemographicsItem.DetailsClass.IImplementation, _
                __CustomerDemographicsItem.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __CustomerDemographicsItem.DetailsClass.PropertySetProperties.CustomerTypeID
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __CustomerDemographicsItemEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass).Entry( _
                    AddressOf __CustomerDemographicsItem.DetailsClass.__CustomerDemographicsItem_CreateNew, _
                    AddressOf __CustomerDemographicsItem.DetailsClass.__CustomerDemographicsItem_Created, _
                    AddressOf __CustomerDemographicsItem.DetailsClass.__CustomerDemographicsItem_AllowSaveWithErrors)
            Private Shared Function __CustomerDemographicsItem_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __CustomerDemographicsItem)) As __CustomerDemographicsItem
                Return New __CustomerDemographicsItem(es)
            End Function
            Private Shared Sub __CustomerDemographicsItem_Created(e As __CustomerDemographicsItem)
                e.CustomerDemographicsItem_Created()
            End Sub
            Private Shared Function __CustomerDemographicsItem_AllowSaveWithErrors(e As __CustomerDemographicsItem) As Boolean
                Dim result As Boolean = False
                e.CustomerDemographicsItem_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __CustomerDemographicsItem.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property CustomerTypeID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomerDemographicsItem.DetailsClass.PropertySetProperties.CustomerTypeID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property CustomerDesc As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomerDemographicsItem.DetailsClass.PropertySetProperties.CustomerDesc),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property CustomerCustomerDemo As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, Global.LightSwitchApplication.CustomerCustomerDemoItem)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CustomerDemographicsItem.DetailsClass.PropertySetProperties.CustomerCustomerDemo),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, Global.LightSwitchApplication.CustomerCustomerDemoItem))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property CustomerTypeID As String
                Shadows Property CustomerDesc As String
                Shadows ReadOnly Property CustomerCustomerDemo As Global.System.Collections.IEnumerable
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CustomerTypeID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, String).Entry( _
                        "CustomerTypeID", _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerTypeID_Stub, _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerTypeID_ComputeIsReadOnly, _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerTypeID_Validate, _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerTypeID_GetImplementationValue, _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerTypeID_SetImplementationValue, _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerTypeID_OnValueChanged)
                Private Shared Sub _CustomerTypeID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomerDemographicsItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, String).Data), d As __CustomerDemographicsItem.DetailsClass, sf As Object)
                    c(d, d._CustomerTypeID, sf)
                End Sub
                Private Shared Function _CustomerTypeID_ComputeIsReadOnly(e As __CustomerDemographicsItem) As Boolean
                    Dim result As Boolean = False
                    e.CustomerTypeID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CustomerTypeID_Validate(e As __CustomerDemographicsItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CustomerTypeID_Validate(r)
                End Sub
                Private Shared Function _CustomerTypeID_GetImplementationValue(d As __CustomerDemographicsItem.DetailsClass) As String
                    Return d.ImplementationEntity.CustomerTypeID
                End Function
                Private Shared Sub _CustomerTypeID_SetImplementationValue(d As __CustomerDemographicsItem.DetailsClass, v As String)
                    d.ImplementationEntity.CustomerTypeID = v
                End Sub
                Private Shared Sub _CustomerTypeID_OnValueChanged(e As __CustomerDemographicsItem)
                    e.CustomerTypeID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CustomerDesc As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, String).Entry( _
                        "CustomerDesc", _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerDesc_Stub, _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerDesc_ComputeIsReadOnly, _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerDesc_Validate, _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerDesc_GetImplementationValue, _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerDesc_SetImplementationValue, _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerDesc_OnValueChanged)
                Private Shared Sub _CustomerDesc_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomerDemographicsItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, String).Data), d As __CustomerDemographicsItem.DetailsClass, sf As Object)
                    c(d, d._CustomerDesc, sf)
                End Sub
                Private Shared Function _CustomerDesc_ComputeIsReadOnly(e As __CustomerDemographicsItem) As Boolean
                    Dim result As Boolean = False
                    e.CustomerDesc_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CustomerDesc_Validate(e As __CustomerDemographicsItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CustomerDesc_Validate(r)
                End Sub
                Private Shared Function _CustomerDesc_GetImplementationValue(d As __CustomerDemographicsItem.DetailsClass) As String
                    Return d.ImplementationEntity.CustomerDesc
                End Function
                Private Shared Sub _CustomerDesc_SetImplementationValue(d As __CustomerDemographicsItem.DetailsClass, v As String)
                    d.ImplementationEntity.CustomerDesc = v
                End Sub
                Private Shared Sub _CustomerDesc_OnValueChanged(e As __CustomerDemographicsItem)
                    e.CustomerDesc_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CustomerCustomerDemo As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, Global.LightSwitchApplication.CustomerCustomerDemoItem).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, Global.LightSwitchApplication.CustomerCustomerDemoItem).Entry( _
                        "CustomerCustomerDemo", _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerCustomerDemo_Stub, _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerCustomerDemo_GetReferencedEntities, _
                        AddressOf __CustomerDemographicsItem.DetailsClass.PropertySetProperties._CustomerCustomerDemo_GetEntityCollection)
                Private Shared Sub _CustomerCustomerDemo_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CustomerDemographicsItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, Global.LightSwitchApplication.CustomerCustomerDemoItem).Data), d As __CustomerDemographicsItem.DetailsClass, sf As Object)
                    c(d, d._CustomerCustomerDemo, sf)
                End Sub
                Private Shared Function _CustomerCustomerDemo_GetReferencedEntities(d As __CustomerDemographicsItem.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.CustomerCustomerDemoItem)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.CustomerCustomerDemoItem, Global.LightSwitchApplication.CustomerCustomerDemoItem.DetailsClass)(__CustomerDemographicsItem.DetailsClass.PropertySetProperties.CustomerCustomerDemo, d._CustomerCustomerDemo)
                End Function
                Private Shared Function _CustomerCustomerDemo_GetEntityCollection(d As __CustomerDemographicsItem.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.CustomerCustomerDemo
                End Function
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CustomerTypeID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CustomerDesc As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CustomerCustomerDemo As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CustomerDemographicsItem, __CustomerDemographicsItem.DetailsClass, Global.LightSwitchApplication.CustomerCustomerDemoItem).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
