
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __ShippersItem = LightSwitchApplication.ShippersItem

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No hay ninguna descripción modelada
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Public NotInheritable Partial Class ShippersItem
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __ShippersItem, __ShippersItem.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Inicializa una nueva instancia de la entidad ShippersItem.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __ShippersItem))
            MyBase.New(entitySet)
            
            __ShippersItem.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ShippersItem_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ShippersItem_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return TryCast(Global.LightSwitchApplication.Application.Current, Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace))
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ShipperID As Integer
            Get
                Return __ShippersItem.DetailsClass.GetValue(Me, __ShippersItem.DetailsClass.PropertySetProperties.ShipperID)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ShipperID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ShipperID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ShipperID_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CompanyName As String
            Get
                Return __ShippersItem.DetailsClass.GetValue(Me, __ShippersItem.DetailsClass.PropertySetProperties.CompanyName)
            End Get
            Set
                __ShippersItem.DetailsClass.SetValue(Me, __ShippersItem.DetailsClass.PropertySetProperties.CompanyName, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CompanyName_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CompanyName_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CompanyName_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Phone As String
            Get
                Return __ShippersItem.DetailsClass.GetValue(Me, __ShippersItem.DetailsClass.PropertySetProperties.Phone)
            End Get
            Set
                __ShippersItem.DetailsClass.SetValue(Me, __ShippersItem.DetailsClass.PropertySetProperties.Phone, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Phone_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Orders As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.OrdersItem)
            Get
                Return __ShippersItem.DetailsClass.GetValue(Me, __ShippersItem.DetailsClass.PropertySetProperties.Orders)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property OrdersQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.OrdersItem)
            Get
                Return __ShippersItem.DetailsClass.GetQuery(Me, __ShippersItem.DetailsClass.PropertySetProperties.Orders)
            End Get
        End Property

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ChoferCollection As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.Chofer)
            Get
                Return __ShippersItem.DetailsClass.GetValue(Me, __ShippersItem.DetailsClass.PropertySetProperties.ChoferCollection)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ChoferCollectionQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Chofer)
            Get
                Return __ShippersItem.DetailsClass.GetQuery(Me, __ShippersItem.DetailsClass.PropertySetProperties.ChoferCollection)
            End Get
        End Property

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __ShippersItem, _
                __ShippersItem.DetailsClass, _
                __ShippersItem.DetailsClass.IImplementation, _
                __ShippersItem.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __ShippersItem, __ShippersItem.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __ShippersItem, __ShippersItem.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __ShippersItem.DetailsClass.PropertySetProperties.ShipperID
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __ShippersItemEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __ShippersItem, __ShippersItem.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __ShippersItem, __ShippersItem.DetailsClass).Entry( _
                    AddressOf __ShippersItem.DetailsClass.__ShippersItem_CreateNew, _
                    AddressOf __ShippersItem.DetailsClass.__ShippersItem_Created, _
                    AddressOf __ShippersItem.DetailsClass.__ShippersItem_AllowSaveWithErrors)
            Private Shared Function __ShippersItem_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __ShippersItem)) As __ShippersItem
                Return New __ShippersItem(es)
            End Function
            Private Shared Sub __ShippersItem_Created(e As __ShippersItem)
                e.ShippersItem_Created()
            End Sub
            Private Shared Function __ShippersItem_AllowSaveWithErrors(e As __ShippersItem) As Boolean
                Dim result As Boolean = False
                e.ShippersItem_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __ShippersItem, __ShippersItem.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __ShippersItem, __ShippersItem.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __ShippersItem.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __ShippersItem, __ShippersItem.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property ShipperID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ShippersItem.DetailsClass.PropertySetProperties.ShipperID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property CompanyName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ShippersItem.DetailsClass.PropertySetProperties.CompanyName),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Phone As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ShippersItem.DetailsClass.PropertySetProperties.Phone),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Orders As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Global.LightSwitchApplication.OrdersItem)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ShippersItem.DetailsClass.PropertySetProperties.Orders),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Global.LightSwitchApplication.OrdersItem))
                    End Get
                End Property
                
                Public ReadOnly Property ChoferCollection As Global.Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Global.LightSwitchApplication.Chofer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__ShippersItem.DetailsClass.PropertySetProperties.ChoferCollection),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Global.LightSwitchApplication.Chofer))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows ReadOnly Property ShipperID As Integer
                Shadows Property CompanyName As String
                Shadows Property Phone As String
                Shadows ReadOnly Property Orders As Global.System.Collections.IEnumerable
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ShipperID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Integer).Entry( _
                        "ShipperID", _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._ShipperID_Stub, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._ShipperID_ComputeIsReadOnly, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._ShipperID_Validate, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._ShipperID_GetImplementationValue, _
                        Nothing, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._ShipperID_OnValueChanged)
                Private Shared Sub _ShipperID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ShippersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Integer).Data), d As __ShippersItem.DetailsClass, sf As Object)
                    c(d, d._ShipperID, sf)
                End Sub
                Private Shared Function _ShipperID_ComputeIsReadOnly(e As __ShippersItem) As Boolean
                    Dim result As Boolean = False
                    e.ShipperID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ShipperID_Validate(e As __ShippersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ShipperID_Validate(r)
                End Sub
                Private Shared Function _ShipperID_GetImplementationValue(d As __ShippersItem.DetailsClass) As Integer
                    Return d.ImplementationEntity.ShipperID
                End Function
                Private Shared Sub _ShipperID_OnValueChanged(e As __ShippersItem)
                    e.ShipperID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CompanyName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, String).Entry( _
                        "CompanyName", _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._CompanyName_Stub, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._CompanyName_ComputeIsReadOnly, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._CompanyName_Validate, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._CompanyName_GetImplementationValue, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._CompanyName_SetImplementationValue, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._CompanyName_OnValueChanged)
                Private Shared Sub _CompanyName_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ShippersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, String).Data), d As __ShippersItem.DetailsClass, sf As Object)
                    c(d, d._CompanyName, sf)
                End Sub
                Private Shared Function _CompanyName_ComputeIsReadOnly(e As __ShippersItem) As Boolean
                    Dim result As Boolean = False
                    e.CompanyName_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CompanyName_Validate(e As __ShippersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CompanyName_Validate(r)
                End Sub
                Private Shared Function _CompanyName_GetImplementationValue(d As __ShippersItem.DetailsClass) As String
                    Return d.ImplementationEntity.CompanyName
                End Function
                Private Shared Sub _CompanyName_SetImplementationValue(d As __ShippersItem.DetailsClass, v As String)
                    d.ImplementationEntity.CompanyName = v
                End Sub
                Private Shared Sub _CompanyName_OnValueChanged(e As __ShippersItem)
                    e.CompanyName_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Phone As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, String).Entry( _
                        "Phone", _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._Phone_Stub, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._Phone_ComputeIsReadOnly, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._Phone_Validate, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._Phone_GetImplementationValue, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._Phone_SetImplementationValue, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._Phone_OnValueChanged)
                Private Shared Sub _Phone_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ShippersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, String).Data), d As __ShippersItem.DetailsClass, sf As Object)
                    c(d, d._Phone, sf)
                End Sub
                Private Shared Function _Phone_ComputeIsReadOnly(e As __ShippersItem) As Boolean
                    Dim result As Boolean = False
                    e.Phone_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Phone_Validate(e As __ShippersItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Phone_Validate(r)
                End Sub
                Private Shared Function _Phone_GetImplementationValue(d As __ShippersItem.DetailsClass) As String
                    Return d.ImplementationEntity.Phone
                End Function
                Private Shared Sub _Phone_SetImplementationValue(d As __ShippersItem.DetailsClass, v As String)
                    d.ImplementationEntity.Phone = v
                End Sub
                Private Shared Sub _Phone_OnValueChanged(e As __ShippersItem)
                    e.Phone_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Orders As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Global.LightSwitchApplication.OrdersItem).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Global.LightSwitchApplication.OrdersItem).Entry( _
                        "Orders", _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._Orders_Stub, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._Orders_GetReferencedEntities, _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._Orders_GetEntityCollection)
                Private Shared Sub _Orders_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ShippersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Global.LightSwitchApplication.OrdersItem).Data), d As __ShippersItem.DetailsClass, sf As Object)
                    c(d, d._Orders, sf)
                End Sub
                Private Shared Function _Orders_GetReferencedEntities(d As __ShippersItem.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.OrdersItem)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.OrdersItem, Global.LightSwitchApplication.OrdersItem.DetailsClass)(__ShippersItem.DetailsClass.PropertySetProperties.Orders, d._Orders)
                End Function
                Private Shared Function _Orders_GetEntityCollection(d As __ShippersItem.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Orders
                End Function
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ChoferCollection As Global.Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Global.LightSwitchApplication.Chofer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Global.LightSwitchApplication.Chofer).Entry( _
                        "ChoferCollection", _
                        AddressOf __ShippersItem.DetailsClass.PropertySetProperties._ChoferCollection_Stub)
                Private Shared Sub _ChoferCollection_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __ShippersItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Global.LightSwitchApplication.Chofer).Data), d As __ShippersItem.DetailsClass, sf As Object)
                    c(d, d._ChoferCollection, sf)
                End Sub
     
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ShipperID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CompanyName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Phone As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __ShippersItem, __ShippersItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Orders As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Global.LightSwitchApplication.OrdersItem).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ChoferCollection As Global.Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty(Of __ShippersItem, __ShippersItem.DetailsClass, Global.LightSwitchApplication.Chofer).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
