
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __EmployeeTerritoriesItem = LightSwitchApplication.EmployeeTerritoriesItem

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No hay ninguna descripción modelada
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Public NotInheritable Partial Class EmployeeTerritoriesItem
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Inicializa una nueva instancia de la entidad EmployeeTerritoriesItem.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __EmployeeTerritoriesItem))
            MyBase.New(entitySet)
            
            __EmployeeTerritoriesItem.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EmployeeTerritoriesItem_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EmployeeTerritoriesItem_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return TryCast(Global.LightSwitchApplication.Application.Current, Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace))
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property EmployeeID As Integer
            Get
                Return __EmployeeTerritoriesItem.DetailsClass.GetValue(Me, __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.EmployeeID)
            End Get
            Set
                __EmployeeTerritoriesItem.DetailsClass.SetValue(Me, __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.EmployeeID, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EmployeeID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EmployeeID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EmployeeID_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property TerritoryID As String
            Get
                Return __EmployeeTerritoriesItem.DetailsClass.GetValue(Me, __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.TerritoryID)
            End Get
            Set
                __EmployeeTerritoriesItem.DetailsClass.SetValue(Me, __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.TerritoryID, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub TerritoryID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub TerritoryID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub TerritoryID_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property EmployeesItem As Global.LightSwitchApplication.EmployeesItem
            Get
                Return __EmployeeTerritoriesItem.DetailsClass.GetValue(Me, __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.EmployeesItem)
            End Get
            Set
                __EmployeeTerritoriesItem.DetailsClass.SetValue(Me, __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.EmployeesItem, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EmployeesItem_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EmployeesItem_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub EmployeesItem_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property TerritoriesItem As Global.LightSwitchApplication.TerritoriesItem
            Get
                Return __EmployeeTerritoriesItem.DetailsClass.GetValue(Me, __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.TerritoriesItem)
            End Get
            Set
                __EmployeeTerritoriesItem.DetailsClass.SetValue(Me, __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.TerritoriesItem, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub TerritoriesItem_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub TerritoriesItem_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub TerritoriesItem_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __EmployeeTerritoriesItem, _
                __EmployeeTerritoriesItem.DetailsClass, _
                __EmployeeTerritoriesItem.DetailsClass.IImplementation, _
                __EmployeeTerritoriesItem.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.EmployeeID
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __EmployeeTerritoriesItemEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass).Entry( _
                    AddressOf __EmployeeTerritoriesItem.DetailsClass.__EmployeeTerritoriesItem_CreateNew, _
                    AddressOf __EmployeeTerritoriesItem.DetailsClass.__EmployeeTerritoriesItem_Created, _
                    AddressOf __EmployeeTerritoriesItem.DetailsClass.__EmployeeTerritoriesItem_AllowSaveWithErrors)
            Private Shared Function __EmployeeTerritoriesItem_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __EmployeeTerritoriesItem)) As __EmployeeTerritoriesItem
                Return New __EmployeeTerritoriesItem(es)
            End Function
            Private Shared Sub __EmployeeTerritoriesItem_Created(e As __EmployeeTerritoriesItem)
                e.EmployeeTerritoriesItem_Created()
            End Sub
            Private Shared Function __EmployeeTerritoriesItem_AllowSaveWithErrors(e As __EmployeeTerritoriesItem) As Boolean
                Dim result As Boolean = False
                e.EmployeeTerritoriesItem_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __EmployeeTerritoriesItem.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property EmployeeID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.EmployeeID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property TerritoryID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.TerritoryID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property EmployeesItem As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Global.LightSwitchApplication.EmployeesItem)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.EmployeesItem),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Global.LightSwitchApplication.EmployeesItem))
                    End Get
                End Property
                
                Public ReadOnly Property TerritoriesItem As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Global.LightSwitchApplication.TerritoriesItem)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.TerritoriesItem),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Global.LightSwitchApplication.TerritoriesItem))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property EmployeeID As Integer
                Shadows Property TerritoryID As String
                Shadows Property EmployeesItem As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                Shadows Property TerritoriesItem As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly EmployeeID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Integer).Entry( _
                        "EmployeeID", _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeeID_Stub, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeeID_ComputeIsReadOnly, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeeID_Validate, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeeID_GetImplementationValue, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeeID_SetImplementationValue, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeeID_OnValueChanged)
                Private Shared Sub _EmployeeID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __EmployeeTerritoriesItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Integer).Data), d As __EmployeeTerritoriesItem.DetailsClass, sf As Object)
                    c(d, d._EmployeeID, sf)
                End Sub
                Private Shared Function _EmployeeID_ComputeIsReadOnly(e As __EmployeeTerritoriesItem) As Boolean
                    Dim result As Boolean = False
                    e.EmployeeID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _EmployeeID_Validate(e As __EmployeeTerritoriesItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.EmployeeID_Validate(r)
                End Sub
                Private Shared Function _EmployeeID_GetImplementationValue(d As __EmployeeTerritoriesItem.DetailsClass) As Integer
                    Return d.ImplementationEntity.EmployeeID
                End Function
                Private Shared Sub _EmployeeID_SetImplementationValue(d As __EmployeeTerritoriesItem.DetailsClass, v As Integer)
                    d.ImplementationEntity.EmployeeID = v
                End Sub
                Private Shared Sub _EmployeeID_OnValueChanged(e As __EmployeeTerritoriesItem)
                    e.EmployeeID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly TerritoryID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, String).Entry( _
                        "TerritoryID", _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoryID_Stub, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoryID_ComputeIsReadOnly, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoryID_Validate, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoryID_GetImplementationValue, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoryID_SetImplementationValue, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoryID_OnValueChanged)
                Private Shared Sub _TerritoryID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __EmployeeTerritoriesItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, String).Data), d As __EmployeeTerritoriesItem.DetailsClass, sf As Object)
                    c(d, d._TerritoryID, sf)
                End Sub
                Private Shared Function _TerritoryID_ComputeIsReadOnly(e As __EmployeeTerritoriesItem) As Boolean
                    Dim result As Boolean = False
                    e.TerritoryID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _TerritoryID_Validate(e As __EmployeeTerritoriesItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.TerritoryID_Validate(r)
                End Sub
                Private Shared Function _TerritoryID_GetImplementationValue(d As __EmployeeTerritoriesItem.DetailsClass) As String
                    Return d.ImplementationEntity.TerritoryID
                End Function
                Private Shared Sub _TerritoryID_SetImplementationValue(d As __EmployeeTerritoriesItem.DetailsClass, v As String)
                    d.ImplementationEntity.TerritoryID = v
                End Sub
                Private Shared Sub _TerritoryID_OnValueChanged(e As __EmployeeTerritoriesItem)
                    e.TerritoryID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly EmployeesItem As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Global.LightSwitchApplication.EmployeesItem).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Global.LightSwitchApplication.EmployeesItem).Entry( _
                        "EmployeesItem", _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeesItem_Stub, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeesItem_ComputeIsReadOnly, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeesItem_Validate, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeesItem_GetCoreImplementationValue, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeesItem_GetImplementationValue, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeesItem_SetImplementationValue, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeesItem_Refresh, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._EmployeesItem_OnValueChanged)
                Private Shared Sub _EmployeesItem_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __EmployeeTerritoriesItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Global.LightSwitchApplication.EmployeesItem).Data), d As __EmployeeTerritoriesItem.DetailsClass, sf As Object)
                    c(d, d._EmployeesItem, sf)
                End Sub
                Private Shared Function _EmployeesItem_ComputeIsReadOnly(e As __EmployeeTerritoriesItem) As Boolean
                    Dim result As Boolean = False
                    e.EmployeesItem_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _EmployeesItem_Validate(e As __EmployeeTerritoriesItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.EmployeesItem_Validate(r)
                End Sub
                Private Shared Function _EmployeesItem_GetCoreImplementationValue(d as __EmployeeTerritoriesItem.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.EmployeesItem
                End Function
                Private Shared Function _EmployeesItem_GetImplementationValue(d as __EmployeeTerritoriesItem.DetailsClass) As Global.LightSwitchApplication.EmployeesItem
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.EmployeesItem, Global.LightSwitchApplication.EmployeesItem.DetailsClass)(__EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.EmployeesItem, d._EmployeesItem)
                End Function
                Private Shared Sub _EmployeesItem_SetImplementationValue(d As __EmployeeTerritoriesItem.DetailsClass, v As Global.LightSwitchApplication.EmployeesItem)
                    d.SetImplementationValue(__EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.EmployeesItem, d._EmployeesItem, Sub(i, ev) i.EmployeesItem = ev, v)
                End Sub
                Private Shared Sub _EmployeesItem_Refresh(d As __EmployeeTerritoriesItem.DetailsClass)
                    d.RefreshNavigationProperty(__EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.EmployeesItem, d._EmployeesItem)
                End Sub
                Private Shared Sub _EmployeesItem_OnValueChanged(e As __EmployeeTerritoriesItem)
                    e.EmployeesItem_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly TerritoriesItem As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Global.LightSwitchApplication.TerritoriesItem).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Global.LightSwitchApplication.TerritoriesItem).Entry( _
                        "TerritoriesItem", _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoriesItem_Stub, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoriesItem_ComputeIsReadOnly, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoriesItem_Validate, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoriesItem_GetCoreImplementationValue, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoriesItem_GetImplementationValue, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoriesItem_SetImplementationValue, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoriesItem_Refresh, _
                        AddressOf __EmployeeTerritoriesItem.DetailsClass.PropertySetProperties._TerritoriesItem_OnValueChanged)
                Private Shared Sub _TerritoriesItem_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __EmployeeTerritoriesItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Global.LightSwitchApplication.TerritoriesItem).Data), d As __EmployeeTerritoriesItem.DetailsClass, sf As Object)
                    c(d, d._TerritoriesItem, sf)
                End Sub
                Private Shared Function _TerritoriesItem_ComputeIsReadOnly(e As __EmployeeTerritoriesItem) As Boolean
                    Dim result As Boolean = False
                    e.TerritoriesItem_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _TerritoriesItem_Validate(e As __EmployeeTerritoriesItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.TerritoriesItem_Validate(r)
                End Sub
                Private Shared Function _TerritoriesItem_GetCoreImplementationValue(d as __EmployeeTerritoriesItem.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.TerritoriesItem
                End Function
                Private Shared Function _TerritoriesItem_GetImplementationValue(d as __EmployeeTerritoriesItem.DetailsClass) As Global.LightSwitchApplication.TerritoriesItem
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.TerritoriesItem, Global.LightSwitchApplication.TerritoriesItem.DetailsClass)(__EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.TerritoriesItem, d._TerritoriesItem)
                End Function
                Private Shared Sub _TerritoriesItem_SetImplementationValue(d As __EmployeeTerritoriesItem.DetailsClass, v As Global.LightSwitchApplication.TerritoriesItem)
                    d.SetImplementationValue(__EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.TerritoriesItem, d._TerritoriesItem, Sub(i, ev) i.TerritoriesItem = ev, v)
                End Sub
                Private Shared Sub _TerritoriesItem_Refresh(d As __EmployeeTerritoriesItem.DetailsClass)
                    d.RefreshNavigationProperty(__EmployeeTerritoriesItem.DetailsClass.PropertySetProperties.TerritoriesItem, d._TerritoriesItem)
                End Sub
                Private Shared Sub _TerritoriesItem_OnValueChanged(e As __EmployeeTerritoriesItem)
                    e.TerritoriesItem_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _EmployeeID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _TerritoryID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _EmployeesItem As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Global.LightSwitchApplication.EmployeesItem).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _TerritoriesItem As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __EmployeeTerritoriesItem, __EmployeeTerritoriesItem.DetailsClass, Global.LightSwitchApplication.TerritoriesItem).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
