'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Nombre de archivo original:
'Fecha de generación: 27/11/2018 17:08:35
Namespace LightSwitchApplication.Implementation
    '''<summary>
    '''No hay comentarios para ApplicationData en el esquema.
    '''</summary>
    Partial Public Class ApplicationData
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
        '''<summary>
        '''Inicializar un nuevo objeto ApplicationData.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub New(ByVal serviceRoot As Global.System.Uri)
            MyBase.New(serviceRoot, Global.System.Data.Services.Common.DataServiceProtocolVersion.V3)
            Me.ResolveName = AddressOf Me.ResolveNameFromType
            Me.ResolveType = AddressOf Me.ResolveTypeFromName
            Me.OnContextCreated
            Me.Format.LoadServiceModel = AddressOf GeneratedEdmModel.GetInstance
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private Shared ROOTNAMESPACE As String = GetType(ApplicationData).Namespace.Remove(GetType(ApplicationData).Namespace.LastIndexOf("LightSwitchApplication.Implementation"))
        '''<summary>
        '''Como el espacio de nombres configurado para la referencia de este servicio
        '''en Visual Studio es diferente al indicado en el 
        '''esquema de servidor, use mapeadores de tipos para establecer asignaciones entre los dos.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
            Dim resolvedType As Global.System.Type = Me.DefaultResolveType(typeName, "LightSwitchApplication", String.Concat(ROOTNAMESPACE, "LightSwitchApplication.Implementation"))
            If (Not (resolvedType) Is Nothing) Then
                Return resolvedType
            End If
            Return Nothing
        End Function
        '''<summary>
        '''Como el espacio de nombres configurado para la referencia de este servicio
        '''en Visual Studio es diferente al indicado en el 
        '''esquema de servidor, use mapeadores de tipos para establecer asignaciones entre los dos.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
            If clientType.Namespace.Equals(String.Concat(ROOTNAMESPACE, "LightSwitchApplication.Implementation"), Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return String.Concat("LightSwitchApplication.", clientType.Name)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''No hay comentarios para ChoferSet en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property ChoferSet() As Global.System.Data.Services.Client.DataServiceQuery(Of Chofer)
            Get
                If (Me._ChoferSet Is Nothing) Then
                    Me._ChoferSet = MyBase.CreateQuery(Of Chofer)("ChoferSet")
                End If
                Return Me._ChoferSet
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ChoferSet As Global.System.Data.Services.Client.DataServiceQuery(Of Chofer)
        '''<summary>
        '''No hay comentarios para ViajeSet en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property ViajeSet() As Global.System.Data.Services.Client.DataServiceQuery(Of Viaje)
            Get
                If (Me._ViajeSet Is Nothing) Then
                    Me._ViajeSet = MyBase.CreateQuery(Of Viaje)("ViajeSet")
                End If
                Return Me._ViajeSet
            End Get
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ViajeSet As Global.System.Data.Services.Client.DataServiceQuery(Of Viaje)
        '''<summary>
        '''No hay comentarios para ChoferSet en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToChoferSet(ByVal chofer As Chofer)
            MyBase.AddObject("ChoferSet", chofer)
        End Sub
        '''<summary>
        '''No hay comentarios para ViajeSet en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToViajeSet(ByVal viaje As Viaje)
            MyBase.AddObject("ViajeSet", viaje)
        End Sub
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private MustInherit Class GeneratedEdmModel
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Shared ParsedModel As Global.Microsoft.Data.Edm.IEdmModel = LoadModelFromString
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Const ModelPart0 As String = "<edmx:Edmx Version=""1.0"" xmlns:edmx=""http://schemas.microsoft.com/ado/2007/06/edm"& _ 
                "x""><edmx:DataServices xmlns:m=""http://schemas.microsoft.com/ado/2007/08/dataserv"& _ 
                "ices/metadata"" m:DataServiceVersion=""1.0"" m:MaxDataServiceVersion=""3.0""><Schema "& _ 
                "xmlns:annotation=""http://schemas.microsoft.com/ado/2009/02/edm/annotation"" Names"& _ 
                "pace=""LightSwitchApplication"" Alias=""Self"" xmlns=""http://schemas.microsoft.com/a"& _ 
                "do/2008/09/edm""><EntityType Name=""Chofer""><Key><PropertyRef Name=""Id"" /></Key><P"& _ 
                "roperty Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" annotation:StoreGeneratedPat"& _ 
                "tern=""Identity"" /><Property Name=""CUIL"" Type=""Edm.String"" Nullable=""false"" MaxLe"& _ 
                "ngth=""255"" /><Property Name=""Apellido"" Type=""Edm.String"" Nullable=""false"" MaxLen"& _ 
                "gth=""255"" /><Property Name=""Nombre"" Type=""Edm.String"" Nullable=""false"" MaxLength"& _ 
                "=""255"" /><Property Name=""FechaDeNacimiento"" Type=""Edm.DateTime"" Nullable=""false"""& _ 
                " /><Property Name=""ShippersItem_ShipperID"" Type=""Edm.Int32"" Nullable=""false"" /><"& _ 
                "Property Name=""CreatedBy"" Type=""Edm.String"" MaxLength=""255"" /><Property Name=""Cr"& _ 
                "eated"" Type=""Edm.DateTimeOffset"" /><Property Name=""ModifiedBy"" Type=""Edm.String"""& _ 
                " MaxLength=""255"" /><Property Name=""Modified"" Type=""Edm.DateTimeOffset"" /><Proper"& _ 
                "ty Name=""RowVersion"" Type=""Edm.Binary"" Nullable=""false"" ConcurrencyMode=""Fixed"" "& _ 
                "annotation:StoreGeneratedPattern=""Computed"" /><NavigationProperty Name=""ViajeCol"& _ 
                "lection"" Relationship=""LightSwitchApplication.Chofer_Viaje"" ToRole=""Viaje"" FromR"& _ 
                "ole=""Chofer"" /></EntityType><EntityType Name=""Viaje""><Key><PropertyRef Name=""Id"""& _ 
                " /></Key><Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" annotation:StoreG"& _ 
                "eneratedPattern=""Identity"" /><Property Name=""Fecha"" Type=""Edm.DateTime"" Nullable"& _ 
                "=""false"" /><Property Name=""CiudadDestino"" Type=""Edm.String"" Nullable=""false"" Max"& _ 
                "Length=""255"" /><Property Name=""CodigoPostal"" Type=""Edm.Int32"" Nullable=""false"" /"& _ 
                "><Property Name=""Chofer_Viaje"" Type=""Edm.Int32"" Nullable=""false"" /><Property Nam"& _ 
                "e=""CreatedBy"" Type=""Edm.String"" MaxLength=""255"" /><Property Name=""Created"" Type="& _ 
                """Edm.DateTimeOffset"" /><Property Name=""ModifiedBy"" Type=""Edm.String"" MaxLength="""& _ 
                "255"" /><Property Name=""Modified"" Type=""Edm.DateTimeOffset"" /><Property Name=""Row"& _ 
                "Version"" Type=""Edm.Binary"" Nullable=""false"" ConcurrencyMode=""Fixed"" annotation:S"& _ 
                "toreGeneratedPattern=""Computed"" /><NavigationProperty Name=""Chofer"" Relationship"& _ 
                "=""LightSwitchApplication.Chofer_Viaje"" ToRole=""Chofer"" FromRole=""Viaje"" /></Enti"& _ 
                "tyType><Association Name=""Chofer_Viaje""><End Role=""Chofer"" Type=""LightSwitchAppl"& _ 
                "ication.Chofer"" Multiplicity=""1"" /><End Role=""Viaje"" Type=""LightSwitchApplicatio"& _ 
                "n.Viaje"" Multiplicity=""*"" /><ReferentialConstraint><Principal Role=""Chofer""><Pro"& _ 
                "pertyRef Name=""Id"" /></Principal><Dependent Role=""Viaje""><PropertyRef Name=""Chof"& _ 
                "er_Viaje"" /></Dependent></ReferentialConstraint></Association><EntityContainer N"& _ 
                "ame=""ApplicationData"" m:IsDefaultEntityContainer=""true""><EntitySet Name=""ChoferS"& _ 
                "et"" EntityType=""LightSwitchApplication.Chofer"" /><EntitySet Name=""ViajeSet"" Enti"& _ 
                "tyType=""LightSwitchApplication.Viaje"" /><AssociationSet Name=""Chofer_Viaje"" Asso"& _ 
                "ciation=""LightSwitchApplication.Chofer_Viaje""><End Role=""Chofer"" EntitySet=""Chof"& _ 
                "erSet"" /><End Role=""Viaje"" EntitySet=""ViajeSet"" /></AssociationSet><FunctionImpo"& _ 
                "rt Name=""Microsoft_LightSwitch_GetCanInformation"" ReturnType=""Edm.String"" m:Http"& _ 
                "Method=""GET""><Parameter Name=""dataServiceMembers"" Type=""Edm.String"" Mode=""In"" />"& _ 
                "</FunctionImport></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>"
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Shared Function GetConcatenatedEdmxString() As String
                Return String.Concat(ModelPart0)
            End Function
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Public Shared Function GetInstance() As Global.Microsoft.Data.Edm.IEdmModel
                Return ParsedModel
            End Function
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Shared Function LoadModelFromString() As Global.Microsoft.Data.Edm.IEdmModel
                Dim edmxToParse As String = GetConcatenatedEdmxString
                Dim reader As Global.System.Xml.XmlReader = CreateXmlReader(edmxToParse)
                Try 
                    Return Global.Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader)
                Finally
                    CType(reader,Global.System.IDisposable).Dispose
                End Try
            End Function
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
            Private Shared Function CreateXmlReader(ByVal edmxToParse As String) As Global.System.Xml.XmlReader
                Return Global.System.Xml.XmlReader.Create(New Global.System.IO.StringReader(edmxToParse))
            End Function
        End Class
    End Class
    '''<summary>
    '''No hay comentarios para LightSwitchApplication.Chofer en el esquema.
    '''</summary>
    '''<KeyProperties>
    '''Id
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("ChoferSet"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("Id")>  _
    Partial Public Class Chofer
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Crear un nuevo objeto Chofer.
        '''</summary>
        '''<param name="ID">Valor inicial de Id.</param>
        '''<param name="cUIL">Valor inicial de CUIL.</param>
        '''<param name="apellido">Valor inicial de Apellido.</param>
        '''<param name="nombre">Valor inicial de Nombre.</param>
        '''<param name="fechaDeNacimiento">Valor inicial de FechaDeNacimiento.</param>
        '''<param name="shippersItem_ShipperID">Valor inicial de ShippersItem_ShipperID.</param>
        '''<param name="rowVersion">Valor inicial de RowVersion.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateChofer(ByVal ID As Integer, ByVal cUIL As String, ByVal apellido As String, ByVal nombre As String, ByVal fechaDeNacimiento As Date, ByVal shippersItem_ShipperID As Integer, ByVal rowVersion() As Byte) As Chofer
            Dim chofer As Chofer = New Chofer()
            chofer.Id = ID
            chofer.CUIL = cUIL
            chofer.Apellido = apellido
            chofer.Nombre = nombre
            chofer.FechaDeNacimiento = fechaDeNacimiento
            chofer.ShippersItem_ShipperID = shippersItem_ShipperID
            chofer.RowVersion = rowVersion
            Return chofer
        End Function
        '''<summary>
        '''No hay comentarios para la propiedad Id en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Id() As Integer
            Get
                Return Me._Id
            End Get
            Set
                Me.OnIdChanging(value)
                If Object.Equals(Me.Id, value) Then
                    Return
                End If
                Me._Id = value
                Me.OnIdChanged
                Me.OnPropertyChanged("Id")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Id As Integer
        Partial Private Sub OnIdChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnIdChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad CUIL en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property CUIL() As String
            Get
                Return Me._CUIL
            End Get
            Set
                Me.OnCUILChanging(value)
                If Object.Equals(Me.CUIL, value) Then
                    Return
                End If
                Me._CUIL = value
                Me.OnCUILChanged
                Me.OnPropertyChanged("CUIL")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _CUIL As String
        Partial Private Sub OnCUILChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCUILChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad Apellido en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Apellido() As String
            Get
                Return Me._Apellido
            End Get
            Set
                Me.OnApellidoChanging(value)
                If Object.Equals(Me.Apellido, value) Then
                    Return
                End If
                Me._Apellido = value
                Me.OnApellidoChanged
                Me.OnPropertyChanged("Apellido")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Apellido As String
        Partial Private Sub OnApellidoChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnApellidoChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad Nombre en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Nombre() As String
            Get
                Return Me._Nombre
            End Get
            Set
                Me.OnNombreChanging(value)
                If Object.Equals(Me.Nombre, value) Then
                    Return
                End If
                Me._Nombre = value
                Me.OnNombreChanged
                Me.OnPropertyChanged("Nombre")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Nombre As String
        Partial Private Sub OnNombreChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnNombreChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad FechaDeNacimiento en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property FechaDeNacimiento() As Date
            Get
                Return Me._FechaDeNacimiento
            End Get
            Set
                Me.OnFechaDeNacimientoChanging(value)
                If Object.Equals(Me.FechaDeNacimiento, value) Then
                    Return
                End If
                Me._FechaDeNacimiento = value
                Me.OnFechaDeNacimientoChanged
                Me.OnPropertyChanged("FechaDeNacimiento")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _FechaDeNacimiento As Date
        Partial Private Sub OnFechaDeNacimientoChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnFechaDeNacimientoChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad ShippersItem_ShipperID en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShippersItem_ShipperID() As Integer
            Get
                Return Me._ShippersItem_ShipperID
            End Get
            Set
                Me.OnShippersItem_ShipperIDChanging(value)
                If Object.Equals(Me.ShippersItem_ShipperID, value) Then
                    Return
                End If
                Me._ShippersItem_ShipperID = value
                Me.OnShippersItem_ShipperIDChanged
                Me.OnPropertyChanged("ShippersItem_ShipperID")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShippersItem_ShipperID As Integer
        Partial Private Sub OnShippersItem_ShipperIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnShippersItem_ShipperIDChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad CreatedBy en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property CreatedBy() As String
            Get
                Return Me._CreatedBy
            End Get
            Set
                Me.OnCreatedByChanging(value)
                If Object.Equals(Me.CreatedBy, value) Then
                    Return
                End If
                Me._CreatedBy = value
                Me.OnCreatedByChanged
                Me.OnPropertyChanged("CreatedBy")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _CreatedBy As String
        Partial Private Sub OnCreatedByChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCreatedByChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad Created en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Created() As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return Me._Created
            End Get
            Set
                Me.OnCreatedChanging(value)
                If Object.Equals(Me.Created, value) Then
                    Return
                End If
                Me._Created = value
                Me.OnCreatedChanged
                Me.OnPropertyChanged("Created")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
        Partial Private Sub OnCreatedChanging(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
        End Sub
        Partial Private Sub OnCreatedChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad ModifiedBy en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ModifiedBy() As String
            Get
                Return Me._ModifiedBy
            End Get
            Set
                Me.OnModifiedByChanging(value)
                If Object.Equals(Me.ModifiedBy, value) Then
                    Return
                End If
                Me._ModifiedBy = value
                Me.OnModifiedByChanged
                Me.OnPropertyChanged("ModifiedBy")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ModifiedBy As String
        Partial Private Sub OnModifiedByChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnModifiedByChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad Modified en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Modified() As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return Me._Modified
            End Get
            Set
                Me.OnModifiedChanging(value)
                If Object.Equals(Me.Modified, value) Then
                    Return
                End If
                Me._Modified = value
                Me.OnModifiedChanged
                Me.OnPropertyChanged("Modified")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
        Partial Private Sub OnModifiedChanging(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
        End Sub
        Partial Private Sub OnModifiedChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad RowVersion en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property RowVersion() As Byte()
            Get
                If (Not (Me._RowVersion) Is Nothing) Then
                    Return CType(Me._RowVersion.Clone,Byte())
                Else
                    Return Nothing
                End If
            End Get
            Set
                Me.OnRowVersionChanging(value)
                If Object.Equals(Me.RowVersion, value) Then
                    Return
                End If
                Me._RowVersion = value
                Me.OnRowVersionChanged
                Me.OnPropertyChanged("RowVersion")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _RowVersion() As Byte
        Partial Private Sub OnRowVersionChanging(ByVal value() As Byte)
        End Sub
        Partial Private Sub OnRowVersionChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para ViajeCollection en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ViajeCollection() As Global.System.Data.Services.Client.DataServiceCollection(Of Viaje)
            Get
                Me.__ViajeCollection.EnsureValueInitialized
                Return Me._ViajeCollection
            End Get
            Set
                Me._ViajeCollection = value
                Me.OnPropertyChanged("ViajeCollection")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ViajeCollection As Global.System.Data.Services.Client.DataServiceCollection(Of Viaje) = New Global.System.Data.Services.Client.DataServiceCollection(Of Viaje)(Nothing, Global.System.Data.Services.Client.TrackingMode.None)
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''No hay comentarios para LightSwitchApplication.Viaje en el esquema.
    '''</summary>
    '''<KeyProperties>
    '''Id
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("ViajeSet"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("Id")>  _
    Partial Public Class Viaje
        Inherits Global.Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Crear un nuevo objeto Viaje.
        '''</summary>
        '''<param name="ID">Valor inicial de Id.</param>
        '''<param name="fecha">Valor inicial de Fecha.</param>
        '''<param name="ciudadDestino">Valor inicial de CiudadDestino.</param>
        '''<param name="codigoPostal">Valor inicial de CodigoPostal.</param>
        '''<param name="chofer_Viaje">Valor inicial de Chofer_Viaje.</param>
        '''<param name="rowVersion">Valor inicial de RowVersion.</param>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateViaje(ByVal ID As Integer, ByVal fecha As Date, ByVal ciudadDestino As String, ByVal codigoPostal As Integer, ByVal chofer_Viaje As Integer, ByVal rowVersion() As Byte) As Viaje
            Dim viaje As Viaje = New Viaje()
            viaje.Id = ID
            viaje.Fecha = fecha
            viaje.CiudadDestino = ciudadDestino
            viaje.CodigoPostal = codigoPostal
            viaje.Chofer_Viaje = chofer_Viaje
            viaje.RowVersion = rowVersion
            Return viaje
        End Function
        '''<summary>
        '''No hay comentarios para la propiedad Id en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Id() As Integer
            Get
                Return Me._Id
            End Get
            Set
                Me.OnIdChanging(value)
                If Object.Equals(Me.Id, value) Then
                    Return
                End If
                Me._Id = value
                Me.OnIdChanged
                Me.OnPropertyChanged("Id")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Id As Integer
        Partial Private Sub OnIdChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnIdChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad Fecha en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Fecha() As Date
            Get
                Return Me._Fecha
            End Get
            Set
                Me.OnFechaChanging(value)
                If Object.Equals(Me.Fecha, value) Then
                    Return
                End If
                Me._Fecha = value
                Me.OnFechaChanged
                Me.OnPropertyChanged("Fecha")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Fecha As Date
        Partial Private Sub OnFechaChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OnFechaChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad CiudadDestino en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property CiudadDestino() As String
            Get
                Return Me._CiudadDestino
            End Get
            Set
                Me.OnCiudadDestinoChanging(value)
                If Object.Equals(Me.CiudadDestino, value) Then
                    Return
                End If
                Me._CiudadDestino = value
                Me.OnCiudadDestinoChanged
                Me.OnPropertyChanged("CiudadDestino")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _CiudadDestino As String
        Partial Private Sub OnCiudadDestinoChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCiudadDestinoChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad CodigoPostal en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property CodigoPostal() As Integer
            Get
                Return Me._CodigoPostal
            End Get
            Set
                Me.OnCodigoPostalChanging(value)
                If Object.Equals(Me.CodigoPostal, value) Then
                    Return
                End If
                Me._CodigoPostal = value
                Me.OnCodigoPostalChanged
                Me.OnPropertyChanged("CodigoPostal")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _CodigoPostal As Integer
        Partial Private Sub OnCodigoPostalChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnCodigoPostalChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad Chofer_Viaje en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Chofer_Viaje() As Integer
            Get
                Return Me._Chofer_Viaje
            End Get
            Set
                Me.OnChofer_ViajeChanging(value)
                If Object.Equals(Me.Chofer_Viaje, value) Then
                    Return
                End If
                Me._Chofer_Viaje = value
                Me.OnChofer_ViajeChanged
                Me.OnPropertyChanged("Chofer_Viaje")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Chofer_Viaje As Integer
        Partial Private Sub OnChofer_ViajeChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnChofer_ViajeChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad CreatedBy en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property CreatedBy() As String
            Get
                Return Me._CreatedBy
            End Get
            Set
                Me.OnCreatedByChanging(value)
                If Object.Equals(Me.CreatedBy, value) Then
                    Return
                End If
                Me._CreatedBy = value
                Me.OnCreatedByChanged
                Me.OnPropertyChanged("CreatedBy")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _CreatedBy As String
        Partial Private Sub OnCreatedByChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCreatedByChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad Created en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Created() As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return Me._Created
            End Get
            Set
                Me.OnCreatedChanging(value)
                If Object.Equals(Me.Created, value) Then
                    Return
                End If
                Me._Created = value
                Me.OnCreatedChanged
                Me.OnPropertyChanged("Created")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
        Partial Private Sub OnCreatedChanging(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
        End Sub
        Partial Private Sub OnCreatedChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad ModifiedBy en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ModifiedBy() As String
            Get
                Return Me._ModifiedBy
            End Get
            Set
                Me.OnModifiedByChanging(value)
                If Object.Equals(Me.ModifiedBy, value) Then
                    Return
                End If
                Me._ModifiedBy = value
                Me.OnModifiedByChanged
                Me.OnPropertyChanged("ModifiedBy")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ModifiedBy As String
        Partial Private Sub OnModifiedByChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnModifiedByChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad Modified en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Modified() As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return Me._Modified
            End Get
            Set
                Me.OnModifiedChanging(value)
                If Object.Equals(Me.Modified, value) Then
                    Return
                End If
                Me._Modified = value
                Me.OnModifiedChanged
                Me.OnPropertyChanged("Modified")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
        Partial Private Sub OnModifiedChanging(ByVal value As Global.System.Nullable(Of Global.System.DateTimeOffset))
        End Sub
        Partial Private Sub OnModifiedChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para la propiedad RowVersion en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property RowVersion() As Byte()
            Get
                If (Not (Me._RowVersion) Is Nothing) Then
                    Return CType(Me._RowVersion.Clone,Byte())
                Else
                    Return Nothing
                End If
            End Get
            Set
                Me.OnRowVersionChanging(value)
                If Object.Equals(Me.RowVersion, value) Then
                    Return
                End If
                Me._RowVersion = value
                Me.OnRowVersionChanged
                Me.OnPropertyChanged("RowVersion")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _RowVersion() As Byte
        Partial Private Sub OnRowVersionChanging(ByVal value() As Byte)
        End Sub
        Partial Private Sub OnRowVersionChanged()
        End Sub
        '''<summary>
        '''No hay comentarios para Chofer en el esquema.
        '''</summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Chofer() As Chofer
            Get
                Me.__Chofer.EnsureValueInitialized
                Return Me._Chofer
            End Get
            Set
                Dim previous As Chofer = Me.Chofer
                If (previous Is value) Then
                    Return
                End If
                If (Not (previous) Is Nothing) Then
                    Me._Chofer = Nothing
                    Me.__Chofer.OnValueSet
                    previous.ViajeCollection.Remove(Me)
                End If
                If (Not (Me.___Host) Is Nothing) Then
                    If (Not (value) Is Nothing) Then
                        Me.Chofer_Viaje = value.Id
                    Else
                        Me.Chofer_Viaje = CType(Nothing, Integer)
                    End If
                End If
                Me._Chofer = value
                Me.__Chofer.OnValueSet
                If (Not (value) Is Nothing) Then
                    value.__ViajeCollection.Add(Me)
                End If
                Me.___OnPropertyChanged("Chofer")
                Me.OnPropertyChanged("Chofer")
            End Set
        End Property
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Chofer As Chofer
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements Global.System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
End Namespace
