
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __CategoriesItem = LightSwitchApplication.CategoriesItem

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No hay ninguna descripción modelada
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Public NotInheritable Partial Class CategoriesItem
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __CategoriesItem, __CategoriesItem.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Inicializa una nueva instancia de la entidad CategoriesItem.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __CategoriesItem))
            MyBase.New(entitySet)
            
            __CategoriesItem.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CategoriesItem_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CategoriesItem_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return TryCast(Global.LightSwitchApplication.Application.Current, Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace))
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property CategoryID As Integer
            Get
                Return __CategoriesItem.DetailsClass.GetValue(Me, __CategoriesItem.DetailsClass.PropertySetProperties.CategoryID)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CategoryID_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CategoryID_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CategoryID_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CategoryName As String
            Get
                Return __CategoriesItem.DetailsClass.GetValue(Me, __CategoriesItem.DetailsClass.PropertySetProperties.CategoryName)
            End Get
            Set
                __CategoriesItem.DetailsClass.SetValue(Me, __CategoriesItem.DetailsClass.PropertySetProperties.CategoryName, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CategoryName_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CategoryName_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CategoryName_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Description As String
            Get
                Return __CategoriesItem.DetailsClass.GetValue(Me, __CategoriesItem.DetailsClass.PropertySetProperties.Description)
            End Get
            Set
                __CategoriesItem.DetailsClass.SetValue(Me, __CategoriesItem.DetailsClass.PropertySetProperties.Description, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Description_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Description_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Description_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Picture As Byte()
            Get
                Return __CategoriesItem.DetailsClass.GetValue(Me, __CategoriesItem.DetailsClass.PropertySetProperties.Picture)
            End Get
            Set
                __CategoriesItem.DetailsClass.SetValue(Me, __CategoriesItem.DetailsClass.PropertySetProperties.Picture, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Picture_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Picture_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Picture_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Products As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.ProductsItem)
            Get
                Return __CategoriesItem.DetailsClass.GetValue(Me, __CategoriesItem.DetailsClass.PropertySetProperties.Products)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ProductsQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.ProductsItem)
            Get
                Return __CategoriesItem.DetailsClass.GetQuery(Me, __CategoriesItem.DetailsClass.PropertySetProperties.Products)
            End Get
        End Property

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __CategoriesItem, _
                __CategoriesItem.DetailsClass, _
                __CategoriesItem.DetailsClass.IImplementation, _
                __CategoriesItem.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __CategoriesItem, __CategoriesItem.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __CategoriesItem, __CategoriesItem.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __CategoriesItem.DetailsClass.PropertySetProperties.CategoryID
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __CategoriesItemEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __CategoriesItem, __CategoriesItem.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __CategoriesItem, __CategoriesItem.DetailsClass).Entry( _
                    AddressOf __CategoriesItem.DetailsClass.__CategoriesItem_CreateNew, _
                    AddressOf __CategoriesItem.DetailsClass.__CategoriesItem_Created, _
                    AddressOf __CategoriesItem.DetailsClass.__CategoriesItem_AllowSaveWithErrors)
            Private Shared Function __CategoriesItem_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __CategoriesItem)) As __CategoriesItem
                Return New __CategoriesItem(es)
            End Function
            Private Shared Sub __CategoriesItem_Created(e As __CategoriesItem)
                e.CategoriesItem_Created()
            End Sub
            Private Shared Function __CategoriesItem_AllowSaveWithErrors(e As __CategoriesItem) As Boolean
                Dim result As Boolean = False
                e.CategoriesItem_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __CategoriesItem, __CategoriesItem.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __CategoriesItem, __CategoriesItem.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __CategoriesItem.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __CategoriesItem, __CategoriesItem.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property CategoryID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CategoriesItem.DetailsClass.PropertySetProperties.CategoryID),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property CategoryName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CategoriesItem.DetailsClass.PropertySetProperties.CategoryName),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Description As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CategoriesItem.DetailsClass.PropertySetProperties.Description),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Picture As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Byte())
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CategoriesItem.DetailsClass.PropertySetProperties.Picture),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Byte()))
                    End Get
                End Property
                
                Public ReadOnly Property Products As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Global.LightSwitchApplication.ProductsItem)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__CategoriesItem.DetailsClass.PropertySetProperties.Products),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Global.LightSwitchApplication.ProductsItem))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows ReadOnly Property CategoryID As Integer
                Shadows Property CategoryName As String
                Shadows Property Description As String
                Shadows Property Picture As Byte()
                Shadows ReadOnly Property Products As Global.System.Collections.IEnumerable
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CategoryID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Integer).Entry( _
                        "CategoryID", _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._CategoryID_Stub, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._CategoryID_ComputeIsReadOnly, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._CategoryID_Validate, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._CategoryID_GetImplementationValue, _
                        Nothing, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._CategoryID_OnValueChanged)
                Private Shared Sub _CategoryID_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CategoriesItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Integer).Data), d As __CategoriesItem.DetailsClass, sf As Object)
                    c(d, d._CategoryID, sf)
                End Sub
                Private Shared Function _CategoryID_ComputeIsReadOnly(e As __CategoriesItem) As Boolean
                    Dim result As Boolean = False
                    e.CategoryID_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CategoryID_Validate(e As __CategoriesItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CategoryID_Validate(r)
                End Sub
                Private Shared Function _CategoryID_GetImplementationValue(d As __CategoriesItem.DetailsClass) As Integer
                    Return d.ImplementationEntity.CategoryID
                End Function
                Private Shared Sub _CategoryID_OnValueChanged(e As __CategoriesItem)
                    e.CategoryID_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CategoryName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, String).Entry( _
                        "CategoryName", _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._CategoryName_Stub, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._CategoryName_ComputeIsReadOnly, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._CategoryName_Validate, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._CategoryName_GetImplementationValue, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._CategoryName_SetImplementationValue, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._CategoryName_OnValueChanged)
                Private Shared Sub _CategoryName_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CategoriesItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, String).Data), d As __CategoriesItem.DetailsClass, sf As Object)
                    c(d, d._CategoryName, sf)
                End Sub
                Private Shared Function _CategoryName_ComputeIsReadOnly(e As __CategoriesItem) As Boolean
                    Dim result As Boolean = False
                    e.CategoryName_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CategoryName_Validate(e As __CategoriesItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CategoryName_Validate(r)
                End Sub
                Private Shared Function _CategoryName_GetImplementationValue(d As __CategoriesItem.DetailsClass) As String
                    Return d.ImplementationEntity.CategoryName
                End Function
                Private Shared Sub _CategoryName_SetImplementationValue(d As __CategoriesItem.DetailsClass, v As String)
                    d.ImplementationEntity.CategoryName = v
                End Sub
                Private Shared Sub _CategoryName_OnValueChanged(e As __CategoriesItem)
                    e.CategoryName_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Description As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, String).Entry( _
                        "Description", _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Description_Stub, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Description_Validate, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Description_GetImplementationValue, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Description_SetImplementationValue, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Description_OnValueChanged)
                Private Shared Sub _Description_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CategoriesItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, String).Data), d As __CategoriesItem.DetailsClass, sf As Object)
                    c(d, d._Description, sf)
                End Sub
                Private Shared Function _Description_ComputeIsReadOnly(e As __CategoriesItem) As Boolean
                    Dim result As Boolean = False
                    e.Description_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Description_Validate(e As __CategoriesItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Description_Validate(r)
                End Sub
                Private Shared Function _Description_GetImplementationValue(d As __CategoriesItem.DetailsClass) As String
                    Return d.ImplementationEntity.Description
                End Function
                Private Shared Sub _Description_SetImplementationValue(d As __CategoriesItem.DetailsClass, v As String)
                    d.ImplementationEntity.Description = v
                End Sub
                Private Shared Sub _Description_OnValueChanged(e As __CategoriesItem)
                    e.Description_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Picture As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Byte()).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Byte()).Entry( _
                        "Picture", _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Picture_Stub, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Picture_ComputeIsReadOnly, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Picture_Validate, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Picture_GetImplementationValue, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Picture_SetImplementationValue, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Picture_OnValueChanged)
                Private Shared Sub _Picture_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CategoriesItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Byte()).Data), d As __CategoriesItem.DetailsClass, sf As Object)
                    c(d, d._Picture, sf)
                End Sub
                Private Shared Function _Picture_ComputeIsReadOnly(e As __CategoriesItem) As Boolean
                    Dim result As Boolean = False
                    e.Picture_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Picture_Validate(e As __CategoriesItem, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Picture_Validate(r)
                End Sub
                Private Shared Function _Picture_GetImplementationValue(d As __CategoriesItem.DetailsClass) As Byte()
                    Return d.ImplementationEntity.Picture
                End Function
                Private Shared Sub _Picture_SetImplementationValue(d As __CategoriesItem.DetailsClass, v As Byte())
                    d.ImplementationEntity.Picture = v
                End Sub
                Private Shared Sub _Picture_OnValueChanged(e As __CategoriesItem)
                    e.Picture_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Products As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Global.LightSwitchApplication.ProductsItem).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Global.LightSwitchApplication.ProductsItem).Entry( _
                        "Products", _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Products_Stub, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Products_GetReferencedEntities, _
                        AddressOf __CategoriesItem.DetailsClass.PropertySetProperties._Products_GetEntityCollection)
                Private Shared Sub _Products_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __CategoriesItem.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Global.LightSwitchApplication.ProductsItem).Data), d As __CategoriesItem.DetailsClass, sf As Object)
                    c(d, d._Products, sf)
                End Sub
                Private Shared Function _Products_GetReferencedEntities(d As __CategoriesItem.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.ProductsItem)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.ProductsItem, Global.LightSwitchApplication.ProductsItem.DetailsClass)(__CategoriesItem.DetailsClass.PropertySetProperties.Products, d._Products)
                End Function
                Private Shared Function _Products_GetEntityCollection(d As __CategoriesItem.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Products
                End Function
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CategoryID As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CategoryName As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Description As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Picture As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Byte()).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Products As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __CategoriesItem, __CategoriesItem.DetailsClass, Global.LightSwitchApplication.ProductsItem).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
