
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __Viaje = LightSwitchApplication.Viaje

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No hay ninguna descripción modelada
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
    Public NotInheritable Partial Class Viaje
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __Viaje, __Viaje.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Inicializa una nueva instancia de la entidad Viaje.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Viaje))
            MyBase.New(entitySet)
            
            __Viaje.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Viaje_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Viaje_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Obtiene el objeto Application para esta aplicación. El objeto Application proporciona acceso a pantallas activas, métodos para abrir pantallas y acceso al usuario actual.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return TryCast(Global.LightSwitchApplication.Application.Current, Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace))
            End Get
        End Property
        
        ''' <summary>
        ''' Obtiene el área de trabajo de datos contenedora. Dicha área proporciona acceso a todos los orígenes de datos de la aplicación.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Id As Integer
            Get
                Return __Viaje.DetailsClass.GetValue(Me, __Viaje.DetailsClass.PropertySetProperties.Id)
            End Get
            Set
                __Viaje.DetailsClass.SetValue(Me, __Viaje.DetailsClass.PropertySetProperties.Id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Fecha As Date
            Get
                Return __Viaje.DetailsClass.GetValue(Me, __Viaje.DetailsClass.PropertySetProperties.Fecha)
            End Get
            Set
                __Viaje.DetailsClass.SetValue(Me, __Viaje.DetailsClass.PropertySetProperties.Fecha, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Fecha_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Fecha_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Fecha_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CiudadDestino As String
            Get
                Return __Viaje.DetailsClass.GetValue(Me, __Viaje.DetailsClass.PropertySetProperties.CiudadDestino)
            End Get
            Set
                __Viaje.DetailsClass.SetValue(Me, __Viaje.DetailsClass.PropertySetProperties.CiudadDestino, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CiudadDestino_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CiudadDestino_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CiudadDestino_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property CodigoPostal As Integer
            Get
                Return __Viaje.DetailsClass.GetValue(Me, __Viaje.DetailsClass.PropertySetProperties.CodigoPostal)
            End Get
            Set
                __Viaje.DetailsClass.SetValue(Me, __Viaje.DetailsClass.PropertySetProperties.CodigoPostal, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CodigoPostal_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CodigoPostal_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CodigoPostal_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property CreatedBy As String
            Get
                Return __Viaje.DetailsClass.GetValue(Me, __Viaje.DetailsClass.PropertySetProperties.CreatedBy)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub CreatedBy_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return __Viaje.DetailsClass.GetValue(Me, __Viaje.DetailsClass.PropertySetProperties.Created)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Created_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property ModifiedBy As String
            Get
                Return __Viaje.DetailsClass.GetValue(Me, __Viaje.DetailsClass.PropertySetProperties.ModifiedBy)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub ModifiedBy_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
            Get
                Return __Viaje.DetailsClass.GetValue(Me, __Viaje.DetailsClass.PropertySetProperties.Modified)
            End Get
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Modified_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property RowVersion As Byte()
            Get
                Return __Viaje.DetailsClass.GetValue(Me, __Viaje.DetailsClass.PropertySetProperties.RowVersion)
            End Get
            Set
                __Viaje.DetailsClass.SetValue(Me, __Viaje.DetailsClass.PropertySetProperties.RowVersion, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Changed()
        End Sub

        ''' <summary>
        ''' No hay ninguna descripción modelada
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Chofer As Global.LightSwitchApplication.Chofer
            Get
                Return __Viaje.DetailsClass.GetValue(Me, __Viaje.DetailsClass.PropertySetProperties.Chofer)
            End Get
            Set
                __Viaje.DetailsClass.SetValue(Me, __Viaje.DetailsClass.PropertySetProperties.Chofer, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Chofer_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Chofer_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Chofer_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __Viaje, _
                __Viaje.DetailsClass, _
                __Viaje.DetailsClass.IImplementation, _
                __Viaje.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Viaje, __Viaje.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Viaje, __Viaje.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __Viaje.DetailsClass.PropertySetProperties.Id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __ViajeEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Viaje, __Viaje.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __Viaje, __Viaje.DetailsClass).Entry( _
                    AddressOf __Viaje.DetailsClass.__Viaje_CreateNew, _
                    AddressOf __Viaje.DetailsClass.__Viaje_Created, _
                    AddressOf __Viaje.DetailsClass.__Viaje_AllowSaveWithErrors)
            Private Shared Function __Viaje_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __Viaje)) As __Viaje
                Return New __Viaje(es)
            End Function
            Private Shared Sub __Viaje_Created(e As __Viaje)
                e.Viaje_Created()
            End Sub
            Private Shared Function __Viaje_AllowSaveWithErrors(e As __Viaje) As Boolean
                Dim result As Boolean = False
                e.Viaje_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __Viaje, __Viaje.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __Viaje, __Viaje.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __Viaje.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __Viaje, __Viaje.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Viaje.DetailsClass.PropertySetProperties.Id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property Fecha As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Date)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Viaje.DetailsClass.PropertySetProperties.Fecha),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Date))
                    End Get
                End Property
                
                Public ReadOnly Property CiudadDestino As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Viaje.DetailsClass.PropertySetProperties.CiudadDestino),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property CodigoPostal As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Viaje.DetailsClass.PropertySetProperties.CodigoPostal),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Viaje.DetailsClass.PropertySetProperties.CreatedBy),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Viaje.DetailsClass.PropertySetProperties.Created),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)))
                    End Get
                End Property
                
                Public ReadOnly Property ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Viaje.DetailsClass.PropertySetProperties.ModifiedBy),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset))
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Viaje.DetailsClass.PropertySetProperties.Modified),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)))
                    End Get
                End Property
                
                Public ReadOnly Property RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Byte())
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Viaje.DetailsClass.PropertySetProperties.RowVersion),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Byte()))
                    End Get
                End Property
                
                Public ReadOnly Property Chofer As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Viaje, __Viaje.DetailsClass, Global.LightSwitchApplication.Chofer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__Viaje.DetailsClass.PropertySetProperties.Chofer),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Viaje, __Viaje.DetailsClass, Global.LightSwitchApplication.Chofer))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property Id As Integer
                Shadows Property Fecha As Date
                Shadows Property CiudadDestino As String
                Shadows Property CodigoPostal As Integer
                Shadows ReadOnly Property CreatedBy As String
                Shadows ReadOnly Property Created As Global.System.Nullable(Of Global.System.DateTimeOffset)
                Shadows ReadOnly Property ModifiedBy As String
                Shadows ReadOnly Property Modified As Global.System.Nullable(Of Global.System.DateTimeOffset)
                Shadows Property RowVersion As Byte()
                Shadows Property Chofer As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Integer).Entry( _
                        "Id", _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Id_Stub, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Id_Validate, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Id_GetImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Id_SetImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Id_OnValueChanged)
                Private Shared Sub _Id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Viaje.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Integer).Data), d As __Viaje.DetailsClass, sf As Object)
                    c(d, d._Id, sf)
                End Sub
                Private Shared Function _Id_ComputeIsReadOnly(e As __Viaje) As Boolean
                    Dim result As Boolean = False
                    e.Id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Id_Validate(e As __Viaje, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Id_Validate(r)
                End Sub
                Private Shared Function _Id_GetImplementationValue(d As __Viaje.DetailsClass) As Integer
                    Return d.ImplementationEntity.Id
                End Function
                Private Shared Sub _Id_SetImplementationValue(d As __Viaje.DetailsClass, v As Integer)
                    d.ImplementationEntity.Id = v
                End Sub
                Private Shared Sub _Id_OnValueChanged(e As __Viaje)
                    e.Id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Fecha As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Date).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Date).Entry( _
                        "Fecha", _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Fecha_Stub, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Fecha_ComputeIsReadOnly, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Fecha_Validate, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Fecha_GetImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Fecha_SetImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Fecha_OnValueChanged)
                Private Shared Sub _Fecha_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Viaje.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Date).Data), d As __Viaje.DetailsClass, sf As Object)
                    c(d, d._Fecha, sf)
                End Sub
                Private Shared Function _Fecha_ComputeIsReadOnly(e As __Viaje) As Boolean
                    Dim result As Boolean = False
                    e.Fecha_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Fecha_Validate(e As __Viaje, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Fecha_Validate(r)
                End Sub
                Private Shared Function _Fecha_GetImplementationValue(d As __Viaje.DetailsClass) As Date
                    Return d.ImplementationEntity.Fecha
                End Function
                Private Shared Sub _Fecha_SetImplementationValue(d As __Viaje.DetailsClass, v As Date)
                    d.ImplementationEntity.Fecha = __Viaje.DetailsClass.TruncateDate(v)
                End Sub
                Private Shared Sub _Fecha_OnValueChanged(e As __Viaje)
                    e.Fecha_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CiudadDestino As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String).Entry( _
                        "CiudadDestino", _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CiudadDestino_Stub, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CiudadDestino_ComputeIsReadOnly, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CiudadDestino_Validate, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CiudadDestino_GetImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CiudadDestino_SetImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CiudadDestino_OnValueChanged)
                Private Shared Sub _CiudadDestino_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Viaje.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String).Data), d As __Viaje.DetailsClass, sf As Object)
                    c(d, d._CiudadDestino, sf)
                End Sub
                Private Shared Function _CiudadDestino_ComputeIsReadOnly(e As __Viaje) As Boolean
                    Dim result As Boolean = False
                    e.CiudadDestino_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CiudadDestino_Validate(e As __Viaje, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CiudadDestino_Validate(r)
                End Sub
                Private Shared Function _CiudadDestino_GetImplementationValue(d As __Viaje.DetailsClass) As String
                    Return d.ImplementationEntity.CiudadDestino
                End Function
                Private Shared Sub _CiudadDestino_SetImplementationValue(d As __Viaje.DetailsClass, v As String)
                    d.ImplementationEntity.CiudadDestino = v
                End Sub
                Private Shared Sub _CiudadDestino_OnValueChanged(e As __Viaje)
                    e.CiudadDestino_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CodigoPostal As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Integer).Entry( _
                        "CodigoPostal", _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CodigoPostal_Stub, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CodigoPostal_ComputeIsReadOnly, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CodigoPostal_Validate, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CodigoPostal_GetImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CodigoPostal_SetImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CodigoPostal_OnValueChanged)
                Private Shared Sub _CodigoPostal_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Viaje.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Integer).Data), d As __Viaje.DetailsClass, sf As Object)
                    c(d, d._CodigoPostal, sf)
                End Sub
                Private Shared Function _CodigoPostal_ComputeIsReadOnly(e As __Viaje) As Boolean
                    Dim result As Boolean = False
                    e.CodigoPostal_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CodigoPostal_Validate(e As __Viaje, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CodigoPostal_Validate(r)
                End Sub
                Private Shared Function _CodigoPostal_GetImplementationValue(d As __Viaje.DetailsClass) As Integer
                    Return d.ImplementationEntity.CodigoPostal
                End Function
                Private Shared Sub _CodigoPostal_SetImplementationValue(d As __Viaje.DetailsClass, v As Integer)
                    d.ImplementationEntity.CodigoPostal = v
                End Sub
                Private Shared Sub _CodigoPostal_OnValueChanged(e As __Viaje)
                    e.CodigoPostal_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String).Entry( _
                        "CreatedBy", _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CreatedBy_Stub, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CreatedBy_Validate, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue, _
                        Nothing, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged)
                Private Shared Sub _CreatedBy_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Viaje.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String).Data), d As __Viaje.DetailsClass, sf As Object)
                    c(d, d._CreatedBy, sf)
                End Sub
                Private Shared Function _CreatedBy_ComputeIsReadOnly(e As __Viaje) As Boolean
                    Dim result As Boolean = False
                    e.CreatedBy_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _CreatedBy_Validate(e As __Viaje, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.CreatedBy_Validate(r)
                End Sub
                Private Shared Function _CreatedBy_GetImplementationValue(d As __Viaje.DetailsClass) As String
                    Return d.ImplementationEntity.CreatedBy
                End Function
                Private Shared Sub _CreatedBy_OnValueChanged(e As __Viaje)
                    e.CreatedBy_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry( _
                        "Created", _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Created_Stub, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Created_Validate, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Created_GetImplementationValue, _
                        Nothing, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Created_OnValueChanged)
                Private Shared Sub _Created_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Viaje.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data), d As __Viaje.DetailsClass, sf As Object)
                    c(d, d._Created, sf)
                End Sub
                Private Shared Function _Created_ComputeIsReadOnly(e As __Viaje) As Boolean
                    Dim result As Boolean = False
                    e.Created_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Created_Validate(e As __Viaje, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Created_Validate(r)
                End Sub
                Private Shared Function _Created_GetImplementationValue(d As __Viaje.DetailsClass) As Global.System.Nullable(Of Global.System.DateTimeOffset)
                    Return d.ImplementationEntity.Created
                End Function
                Private Shared Sub _Created_OnValueChanged(e As __Viaje)
                    e.Created_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String).Entry( _
                        "ModifiedBy", _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._ModifiedBy_Stub, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._ModifiedBy_Validate, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue, _
                        Nothing, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged)
                Private Shared Sub _ModifiedBy_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Viaje.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String).Data), d As __Viaje.DetailsClass, sf As Object)
                    c(d, d._ModifiedBy, sf)
                End Sub
                Private Shared Function _ModifiedBy_ComputeIsReadOnly(e As __Viaje) As Boolean
                    Dim result As Boolean = False
                    e.ModifiedBy_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _ModifiedBy_Validate(e As __Viaje, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.ModifiedBy_Validate(r)
                End Sub
                Private Shared Function _ModifiedBy_GetImplementationValue(d As __Viaje.DetailsClass) As String
                    Return d.ImplementationEntity.ModifiedBy
                End Function
                Private Shared Sub _ModifiedBy_OnValueChanged(e As __Viaje)
                    e.ModifiedBy_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Entry( _
                        "Modified", _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Modified_Stub, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Modified_Validate, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Modified_GetImplementationValue, _
                        Nothing, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Modified_OnValueChanged)
                Private Shared Sub _Modified_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Viaje.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data), d As __Viaje.DetailsClass, sf As Object)
                    c(d, d._Modified, sf)
                End Sub
                Private Shared Function _Modified_ComputeIsReadOnly(e As __Viaje) As Boolean
                    Dim result As Boolean = False
                    e.Modified_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Modified_Validate(e As __Viaje, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Modified_Validate(r)
                End Sub
                Private Shared Function _Modified_GetImplementationValue(d As __Viaje.DetailsClass) As Global.System.Nullable(Of Global.System.DateTimeOffset)
                    Return d.ImplementationEntity.Modified
                End Function
                Private Shared Sub _Modified_OnValueChanged(e As __Viaje)
                    e.Modified_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Byte()).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Byte()).Entry( _
                        "RowVersion", _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._RowVersion_Stub, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._RowVersion_Validate, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged)
                Private Shared Sub _RowVersion_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Viaje.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Byte()).Data), d As __Viaje.DetailsClass, sf As Object)
                    c(d, d._RowVersion, sf)
                End Sub
                Private Shared Function _RowVersion_ComputeIsReadOnly(e As __Viaje) As Boolean
                    Dim result As Boolean = False
                    e.RowVersion_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _RowVersion_Validate(e As __Viaje, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.RowVersion_Validate(r)
                End Sub
                Private Shared Function _RowVersion_GetImplementationValue(d As __Viaje.DetailsClass) As Byte()
                    Return d.ImplementationEntity.RowVersion
                End Function
                Private Shared Sub _RowVersion_SetImplementationValue(d As __Viaje.DetailsClass, v As Byte())
                    d.ImplementationEntity.RowVersion = v
                End Sub
                Private Shared Sub _RowVersion_OnValueChanged(e As __Viaje)
                    e.RowVersion_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Chofer As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Viaje, __Viaje.DetailsClass, Global.LightSwitchApplication.Chofer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Viaje, __Viaje.DetailsClass, Global.LightSwitchApplication.Chofer).Entry( _
                        "Chofer", _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Chofer_Stub, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Chofer_ComputeIsReadOnly, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Chofer_Validate, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Chofer_GetCoreImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Chofer_GetImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Chofer_SetImplementationValue, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Chofer_Refresh, _
                        AddressOf __Viaje.DetailsClass.PropertySetProperties._Chofer_OnValueChanged)
                Private Shared Sub _Chofer_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __Viaje.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Viaje, __Viaje.DetailsClass, Global.LightSwitchApplication.Chofer).Data), d As __Viaje.DetailsClass, sf As Object)
                    c(d, d._Chofer, sf)
                End Sub
                Private Shared Function _Chofer_ComputeIsReadOnly(e As __Viaje) As Boolean
                    Dim result As Boolean = False
                    e.Chofer_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Chofer_Validate(e As __Viaje, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Chofer_Validate(r)
                End Sub
                Private Shared Function _Chofer_GetCoreImplementationValue(d as __Viaje.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.Chofer
                End Function
                Private Shared Function _Chofer_GetImplementationValue(d as __Viaje.DetailsClass) As Global.LightSwitchApplication.Chofer
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.Chofer, Global.LightSwitchApplication.Chofer.DetailsClass)(__Viaje.DetailsClass.PropertySetProperties.Chofer, d._Chofer)
                End Function
                Private Shared Sub _Chofer_SetImplementationValue(d As __Viaje.DetailsClass, v As Global.LightSwitchApplication.Chofer)
                    d.SetImplementationValue(__Viaje.DetailsClass.PropertySetProperties.Chofer, d._Chofer, Sub(i, ev) i.Chofer = ev, v)
                End Sub
                Private Shared Sub _Chofer_Refresh(d As __Viaje.DetailsClass)
                    d.RefreshNavigationProperty(__Viaje.DetailsClass.PropertySetProperties.Chofer, d._Chofer)
                End Sub
                Private Shared Sub _Chofer_OnValueChanged(e As __Viaje)
                    e.Chofer_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Fecha As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Date).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CiudadDestino As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CodigoPostal As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _CreatedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Created As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _ModifiedBy As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Modified As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Global.System.Nullable(Of Global.System.DateTimeOffset)).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __Viaje, __Viaje.DetailsClass, Byte()).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Chofer As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __Viaje, __Viaje.DetailsClass, Global.LightSwitchApplication.Chofer).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
